### ISSUE TITLE
2 Problems with the "Shorts" tab

### ISSUE THREAD

**Issue by Vipin2003** [cuynu/ytvanced#10]
1. Ad-Blocker works fine in normal videos, but it doesn't work in Shorts tab. After 3-4 Shorts, Ad comes. Pls fix this also.
2. I don't know this is a feature or a big but it exists. If we are viewing "Shorts" and closes the app (also from Recents) and reopens the app, it always starts from the "Shorts" tab instead of the main home page. This won't happen with other tabs (like subscriptions and library). Please check this.

**These points exists in both YT VANCED and YT REVANCED**

**Comment by cuynu** [comment]
1. Shorts are not blocking ads completely and there is no solution for that right now

2. YouTube always starts from "Shorts" tabs instead of home page is normal, its a new features from original YouTube client

**Comment by Vipin2003** [comment]
Is there any way to bypass the start of YT to homepage from shorts tab...if not, then, i think that Dev's should add a option for that. Bcoz some users are use-to with that.

**Comment by cuynu** [comment]
You can use my new YouTube Vanced version 17.41.34, its has a option to force disable Shorts tab on app startup like as YouTube ReVanced.
