### ISSUE TITLE
When in landscape view/full screen, can't scroll in any side panes

### ISSUE THREAD

**Issue by just4747** [cuynu/ytvanced#102]
In latest version 18.01.38 (Monet theme), after a clean install, any time I am in landscape view and full screen video, if I have any of the right-side sidebars showing (comments, description, etc..), I can't scroll up or down in them at all. I can click buttons/links, but scrolling simply does not work. I have volume swipe gestures enabled, but brightness gestures disabled. Everything seems to work fine in portrait orientation.

**Comment by cuynu** [comment]
Turn brightness gestures back on, or disable both. This is a bug from the ReVanced patch.

**Comment by just4747** [comment]
> Turn brightness gestures back on, or disable both. This is a bug from the ReVanced patch.

That works for now, thank you.
