### ISSUE TITLE
[Bug] Screen does not stay off when video is open

### ISSUE THREAD

**Issue by tarres** [cuynu/ytvanced#103]
Environment
===========
Platform:Android
OS Version: 12
YouTube Vanced Version: 18
Vanced MicroG:
Device: Lenovo P11

Description
===========
Whenever the player is open, fullscreen, normal or mini player and I turn off the screen it turns right back on. Doesn't matter if the video is played or paused. 

Steps to reproduce
==================
1. Open YT vanced 
2.select a video
3.turn off screen
4.

Expected result
===============
Screen stays off

Actual result
=============
Screen turns right back on

Screenshots / Videos / Logs
===========================

Notes
=====

**Comment by cuynu** [comment]
Restart your device

**Comment by tarres** [comment]
I tried, no change.

**Comment by cuynu** [comment]
It could be your device software problem

**Comment by tarres** [comment]
Yeah, it's possible. It does not happen with vanilla YouTube though.
