### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Arnaldosilva1** [cuynu/ytvanced#105]
PLEASE FILL OUT THIS FORM, DO NOT CREATE ISSUE WITHOUT THIS FORM, OTHERWISE, ISSUE WILL CLOSE WITHOUT ANY NOTICE OR CONVERT TO DISCUSSION.

Environment
===========
Platform:Android
OS Version:
YouTube Vanced Version:
Vanced MicroG:
Device:

Description
===========

Steps to reproduce
==================
1.
2.
3.
4.

Expected result
===============

Actual result
=============

Screenshots / Videos / Logs
===========================

Notes
=====

**Comment by cuynu** [comment]
Missing necessary information
