### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by luckycdev** [cuynu/ytvanced#108]
PLEASE FILL OUT THIS FORM, DO NOT CREATE ISSUE WITHOUT THIS FORM, OTHERWISE, ISSUE WILL CLOSE WITHOUT ANY NOTICE OR CONVERT TO DISCUSSION.

Environment
===========
Platform:Android
OS Version:13
YouTube Vanced Version:17.28.35
Vanced MicroG:0.2.24.220220
Device:Samsung S22

Description
===========
Whenever I open the YouTube Vanced app it shows There was a problem with the server [429]

Steps to reproduce
==================
1.download non root microg
2.download non root YouTube Vanced 
3.open YouTube Vanced 
4.see the error on home page

Expected result
===============
show feed

Actual result
=============
There was a problem with the server [429]

Screenshots / Videos / Logs
===========================
![Screenshot_20230208_182418_YouTube Vanced.jpg](https://user-images.githubusercontent.com/50680260/217682629-ed47be26-374e-40a6-9be2-5588a94fa9e8.jpg)

Notes
=====
2/8/23

**Comment by luckycdev** [comment]
My friends also had this issue on the same microg, vanced, and os version but now it is fixed. The app works for me now

**Comment by cuynu** [comment]
Its just a server-side problem from Google, but version 17.28.34 are not bulit by me and outdated
