### ISSUE TITLE
[Bug] Video not playing 

### ISSUE THREAD

**Issue by kapilsoni2013** [cuynu/ytvanced#113]
PLEASE FILL OUT THIS FORM, DO NOT CREATE ISSUE WITHOUT THIS FORM, OTHERWISE, ISSUE WILL CLOSE WITHOUT ANY NOTICE OR CONVERT TO DISCUSSION.

Environment
===========
Platform:Android
OS Version:  Android 13
YouTube Vanced Version: v18. 01.38 Black
Vanced MicroG:  0.2.26.225014
Device: OnePlus 10 Pro 5G

Description
===========
Video are loading but when I click on any video it's not playing loader loading infinitely not playing any of the video

Steps to reproduce
==================
1. Open app
2. Try to play any video
3. Never played only infinite loading 
4.

Expected result
===============
Video should play

Actual result
=============
Video is not playing only loader loading 

Screenshots / Videos / Logs
===========================

Notes
=====

**Comment by cuynu** [comment]
Try change another Google account

**Comment by kapilsoni2013** [comment]
Hey it's working with another Google account. 

But why that old account not working? YouTube blocked that account or what? While same account is working in official YouTube application

**Comment by cuynu** [comment]
> Hey it's working with another Google account.
> 
> But why that old account not working? YouTube blocked that account or what? While same account is working in official YouTube application

Google probably blocked playback on your Google account for non-root variant, this is an issue that almost all users in India and Eurrope are experiencing
