### ISSUE TITLE
[Bug] = App is not installing

### ISSUE THREAD

**Issue by alpha-alexxx** [cuynu/ytvanced#116]
Environment
===========
Platform:Android
OS Version: 12
YouTube Vanced Version: 18.01.38 Dark
Vanced MicroG: 0.2.26.225014
Device: Realme - RMX3085

Description
===========
Hii, I want to install the new app by downloading the latest package from here, so i unistalled old apk files from my phone after that installed. Micro G installed without any problem, but as i tried to install Youtube Vanced then i got error that "App not Installed as package conflicts with an existing package."

Steps to reproduce
==================
1. Download the latest Package from github.
2. Remove the both old packages from my phone.
3. Install the Micro G (Status: Ok)
4. Install the Youtube Vanced Apk(Status : Not installed)

Expected result
===============
I expected that the app should be installed without any conflicts as i have done many time before.

Actual result
=============
But the app doesn't install and give the error of confliction: "App not Installed as package conflicts with an existing package."

Screenshots / Videos / Logs
===========================

Notes
=====
Check this issue as soon as possible.

**Comment by cuynu** [comment]
try uninstall update from original youtube, then try again

**Comment by alpha-alexxx** [comment]
> try uninstall update from original youtube, then try again

Hey, It is not working because i have already done it and also tried disabling the YouTube app. But nothing works😮‍💨

**Comment by cuynu** [comment]
> > try uninstall update from original youtube, then try again
> 
> Hey, It is not working because i have already done it and also tried disabling the YouTube app. But nothing works😮‍💨

I need debug which causes this, use ApktoolM and install using session

**Comment by alpha-alexxx** [comment]
> > > try uninstall update from original youtube, then try again
> > 
> > Hey, It is not working because i have already done it and also tried disabling the YouTube app. But nothing works😮‍💨
> 
> I need debug which causes this, use ApktoolM and install using session

Do i need a Laptop in these steps or it is just a simple apk file.

**Comment by alpha-alexxx** [comment]
> > > try uninstall update from original youtube, then try again
> > 
> > Hey, It is not working because i have already done it and also tried disabling the YouTube app. But nothing works😮‍💨
> 
> I need debug which causes this, use ApktoolM and install using session

Ok I got this one but in my Phone there is no app: Installation failed! Error code: 5
INSTALL_FAILED_UPDATE_INCOMPATIBLE: Package com.vanced.android.youtube signatures do not match previously installed version; ignoring!

**Comment by cuynu** [comment]
Find in settings -> manage all apps and find. if you enabled second space or multi-user mode, look to another user or another space

**Comment by alpha-alexxx** [comment]
> Find in settings -> manage all apps. if you enabled second space or multi-user mode, look to another user or another space

Oh my god 😅 thank you 🥰
