### ISSUE TITLE
Can not install Vanced.microG_0.2.25.223212.apk in Nexus6p android 8.0  

### ISSUE THREAD

**Issue by QGB** [cuynu/ytvanced#12]
“There was a problem parsing the package” 解析安装包出现问题

![Screenshot_20220925-012005](https://user-images.githubusercontent.com/8005654/192110807-06b7bf08-7f2c-4a13-a4fe-58150d41845b.png)

**Comment by cuynu** [comment]
Please speak in English language

**Comment by cuynu** [comment]
Free up some space storage

**Comment by cuynu** [comment]
@QGB Install older microg version instead of free up some storage space
