### ISSUE TITLE
[Bug]  YT Music doesn't download  music

### ISSUE THREAD

**Issue by 3DMichal** [cuynu/ytvanced#124]
Environment
===========
Platform:Android
OS Version: 13
YouTube Vanced Music version: 5.39.52
Vanced MicroG: 0.2.26.225014
Device: Galaxy A53

Description
===========
After I click on "Download", nothing shows something like music is downloading.

Expected result
===============
Downloading selected music

Actual result
=============
Not downloading the music.

Screenshots / Videos / Logs
===========================
![Download Folder](https://user-images.githubusercontent.com/92218535/224571183-a96c1b32-a7cf-47fb-9f89-83695b2ad9b7.png)

Notes
=====

**Comment by cuynu** [comment]
use 5.33.51 https://github.com/cuynu/ytvanced/wiki/5.33.51 
A new update can resolve this problem but i'm focusing to make vanced-patches and vanced-integrations so no update at this time. Please use older version

**Comment by 3DMichal** [comment]
> use 5.33.51 https://github.com/cuynu/ytvanced/wiki/5.33.51 A new update can resolve this problem but i'm focusing to make vanced-patches and vanced-integrations so no update at this time. Please use older version

I tried it on the older version but it still doesn't work

**Comment by cuynu** [comment]
> > use 5.33.51 https://github.com/cuynu/ytvanced/wiki/5.33.51 A new update can resolve this problem but i'm focusing to make vanced-patches and vanced-integrations so no update at this time. Please use older version
> 
> I tried it on the older version but it still doesn't work

5.33.51 still downloading here 
![Screenshot_20230314-065953_YouTube Music Vanced](https://user-images.githubusercontent.com/90895715/224888474-41af9beb-084a-4701-b672-71902d6c532b.png)

**Comment by 3DMichal** [comment]
Sorry, for not replying. 
But it still not downloading
![Screenshot_20230325_215344_YouTube Music Vanced](https://user-images.githubusercontent.com/92218535/227741314-58d9173e-80b6-4917-a8c8-bd7520396506.png)
![Screenshot_20230325_215337_YouTube Music Vanced](https://user-images.githubusercontent.com/92218535/227741318-cc88bc64-cf61-42ca-af14-813d81517e02.png)

**Comment by axixa1234** [comment]
same problem, old version doesn't work

**Comment by ghettoflight** [comment]
> use 5.33.51 https://github.com/cuynu/ytvanced/wiki/5.33.51 A new update can resolve this problem but i'm focusing to make vanced-patches and vanced-integrations so no update at this time. Please use older version

I am unable to download as well, it always says premium is required. I've downloaded several different  Vanced variations I've found on Github, NONE have ever supported downloads. If you get those to work, I'll smoke to that.
