### ISSUE TITLE
[Bug] Can't connect to youtube

### ISSUE THREAD

**Issue by ashuk2000** [cuynu/ytvanced#127]
PLEASE FILL OUT THIS FORM, DO NOT CREATE ISSUE WITHOUT THIS FORM, OTHERWISE, ISSUE WILL CLOSE WITHOUT ANY NOTICE OR CONVERT TO DISCUSSION.

Environment
===========
Platform:Android
OS Version: 12
YouTube Vanced Version: 17.03.38
Vanced MicroG: 0.2.24.220220
Device: oppo a53

Description
===========
When the app is opened it says
"Connect to the internet, you're offline. Check your connection"

The problem wasn't there and it just appeared put of nowhere, tried reinstalling with no luck

Steps to reproduce
==================
1. Open the youtube app

Expected result
===============
Should connect to the YouTube servers

Actual result
=============
No connection

Screenshots / Videos / Logs
===========================
https://youtu.be/bD370TUG1kM

Notes
=====
Maybe blocked by google?

**Comment by cuynu** [comment]
Make sure you have use Unofficial version from my repository. Official Team Vanced builds are not supported here

**Comment by cuynu** [comment]
No respond
