### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by SEAL300** [cuynu/ytvanced#130]
Environment
===========
Platform:Android
OS Version:11
YouTube Vanced Version:18.13.37 and previous versions
Magisk Module Download links: from github
Device: oneplus 6 

Description
===========
after some restart the app crash and flashing magisk zip the only way to fix it 

Steps to reproduce
==================
1.restart the phone

Expected result
===============
app start normal 

Actual result
=============
app crashes

Screenshots / Videos / Logs
===========================
will provide if needed

**Comment by cuynu** [comment]
There is no Vanced 13.13.xx+ at this time.
