### ISSUE TITLE
[Bug] Video stops playing after 50 seconds, 1 minute 

### ISSUE THREAD

**Issue by Avtroman** [cuynu/ytvanced#135]
Logout, login can't help
Delete account can't help
YouTube official work OK
Last ReVanced work OK

**Comment by DonOhhhh** [comment]
me too

**Comment by cuynu** [comment]
you don't fill into issue template, pls create new issue with template

**Comment by Nicolas-Gong** [comment]
I have been encountering the same problem as you since yesterday, and I don't know how to solve it. I have to use the official YouTube app.

**Comment by Nicolas-Gong** [comment]
I upgraded from Download YouTube Vanced Unofficial version 18.01.38 Black to Download YouTube Vanced Unofficial version 18.02.33 Black hotfix, and then went to Vanced Setting to enable VP9. I haven't encountered this issue for a while now.
