### ISSUE TITLE
[Bug] Video skipping backward after few minutes, ocasionally stopping and buffering

### ISSUE THREAD

**Issue by SlavomirDurej** [cuynu/ytvanced#142]
PLEASE FILL OUT THIS FORM, DO NOT CREATE ISSUE WITHOUT THIS FORM, OTHERWISE, ISSUE WILL CLOSE WITHOUT ANY NOTICE OR CONVERT TO DISCUSSION.

Environment
===========
Platform: Android
OS Version: 13
YouTube Vanced Version: 18.02.33
Vanced MicroG: 0.2.26.225014
Device: OnePlus 11 5G

Description
===========
I tested this on playing video podcast that was about 1 hours long. It starts playing fine, but after a few minutes it skips backward like 5-6 seconds. This keeps happening repeatedly every maybe 5-6 minutes. Also after few minutes video ocasionally stops and buffers.

Steps to reproduce
==================
1. Load a longer video
2. press play
3. observe what's happening

Expected result
===============
It should play without the issues.

Actual result
=============
Plays with those issues as described.

Screenshots / Videos / Logs
===========================
I could make a video of this happening if needed.

Notes
=====
I did see this advice :
Enable spoof protobuf option on Vanced settings -> Video (If protobuf spoof option is enabled by default, re-enable spoof protobuf option. Buffering problem should fix.
I have a non rooted version (Android.CarOled.v18.02.33_Black) and I don't have this option in my Settings > Vanced Settings > Video Settings?
The only options I see in here are about video quality over Wifi, celular, video speed, Enable Save Video Quality, speed and custom speed.... No option relating to protobuf or VP9 codec.

**Comment by cuynu** [comment]
Please only use AndroidCar variant on actual Android Car devices

**Comment by arickec** [comment]
Hello.  Version 33 works fine.  Thank you for your work.  Is there the possibility of projecting the video in the youtube application of my smart tv?  It has never worked for me.  Only with the original youtube application.

**Comment by cuynu** [comment]
project discontinued, tks for using my builds
