### ISSUE TITLE
[Bug] Not able to download videos 

### ISSUE THREAD

**Issue by Akarshit7** [cuynu/ytvanced#143]
PLEASE FILL OUT THIS FORM, DO NOT CREATE ISSUE WITHOUT THIS FORM, OTHERWISE, ISSUE WILL CLOSE WITHOUT ANY NOTICE OR CONVERT TO DISCUSSION.

Environment
===========
Platform:Android
OS Version:10
YouTube Vanced Version:YouTube.Vanced.v18.02.33_Black_Universal_hotfix
Vanced MicroG:2.24.220220
Device:Asus max pro m1

Description
===========
I am not able to download videos when ever i click the download button it throws a toast message "ussr.razar.youtube_dl" not found

I didn't changed any settings its a complete fresh install
Steps to reproduce
==================
1.press the download button
2.
3.
4.

Expected result
===============
A dialog to be open to sekect to download video

Actual result
=============
The bug mentioned

Screenshots / Videos / Logs
===========================

Notes
=====

**Comment by cuynu** [comment]
Download and Install NewPipe to able download videos or music from here :
https://newpipe.net/#download
After install NewPipe, go to Vanced settings -> Overlay button settings -> Download settings -> Select NewPipe and Save. Download video/music by pressing download icon in video player.

There are some alternative such as PowerTube but its closed source, Seal is open source but its buggy.

**Comment by Akarshit7** [comment]
I just found that only overlay button is giving me error.Otherwise its downloading the vid.
