### ISSUE TITLE
[BUG] Can't install the 18.02.33 Hotfix apk in Oneplus 6

### ISSUE THREAD

**Issue by Aneesh-Ameer** [cuynu/ytvanced#144]
PLEASE FILL OUT THIS FORM, DO NOT CREATE ISSUE WITHOUT THIS FORM, OTHERWISE, ISSUE WILL CLOSE WITHOUT ANY NOTICE OR CONVERT TO DISCUSSION.

Environment
===========
Platform:Android
OS Version:11
YouTube Vanced Version:18.02.33 Hotfix
Magisk Module Download links: 
Device:Oneplus 6

Description
===========
Can't install the latest 18.02.33 Hotfix apk in my daily driver Oneplus 6.Tried all variants, same issue. Says "App not installed".
 
Steps to reproduce
==================
1.Download APK
2.Click Install

Expected result
===============
"App was installed"

Actual result
=============
App not installed

Screenshots / Videos / Logs
===========================

Notes
=====

**Comment by cuynu** [comment]
uninstall previous vanced installed on your device
