### ISSUE TITLE
[Bug] Clips not working

### ISSUE THREAD

**Issue by The-Big-Dededester** [cuynu/ytvanced#145]
PLEASE FILL OUT THIS FORM, DO NOT CREATE ISSUE WITHOUT THIS FORM, OTHERWISE, ISSUE WILL CLOSE WITHOUT ANY NOTICE OR CONVERT TO DISCUSSION.

Environment
===========
Platform:Android
OS Version: 13
YouTube Vanced Version: 18.02.33
Vanced MicroG: 0.2.26.225014
Device: Galaxy A71 5G

Description
===========
Loading clips does not work.

Steps to reproduce
==================
1. Go to the Library tab.
2. Go to My Clips.
3. Click on a created clip to watch it.

Expected result
===============
Video starts playing at time that clip is supposed to start at. Seek bar works as normal.

Actual result
=============
Video starts at 0:00. Seek bar only restarts video.

Screenshots / Videos / Logs
===========================
![Screenshot_20230419_014929](https://user-images.githubusercontent.com/82744193/232978669-06d513ea-5ddb-4256-9d5c-c3ffdaecefdf.png)

Notes
=====
Clips worked on last official version of Youtube Vanced (which I've been using since it shut down).

**Comment by The-Big-Dededester** [comment]
https://youtube.com/clip/Ugkx0MeopC0LUFWyVroDs20pDMF4X6_RKO0p
This is the clip in question. It's meant to start a while into the video.

**Comment by cuynu** [comment]
This was caused by protobuf spoof patch, if you want to use clips, turn off that option. Unfortunately, I'm focusing on my own patch to make Vanced better.

**Comment by The-Big-Dededester** [comment]
Ah, I see. What is the protobuf patch meant to do, anyways?

**Comment by cuynu** [comment]
> Ah, I see. What is the protobuf patch meant to do, anyways?

spoof protobuf is a feature that prevent video playback buffer issue by spoof signature to Google server-side, but for some reason, its cause some other problem

**Comment by The-Big-Dededester** [comment]
I see. Thank you for the help!
