### ISSUE TITLE
[Bug] Playlist skipping

### ISSUE THREAD

**Issue by CharlZe14** [cuynu/ytvanced#146]
PLEASE FILL OUT THIS FORM, DO NOT CREATE ISSUE WITHOUT THIS FORM, OTHERWISE, ISSUE WILL CLOSE WITHOUT ANY NOTICE OR CONVERT TO DISCUSSION.

Environment
===========
Platform:Android
OS Version:
YouTube Vanced Version:
Vanced MicroG:
Device:

Description
===========
Playlists skipping videos when played

Steps to reproduce
==================
1.play video on playlist
2.try to select another video on playlist
3.
4.

Expected result
===============
Selected video should play

Actual result
=============
Video skips and another is played

Screenshots / Videos / Logs
===========================

Notes
=====

**Comment by cuynu** [comment]
Insufficient information, pls re-create new issue
