### ISSUE TITLE
[Bug] Playlist Skipping

### ISSUE THREAD

**Issue by CharlZe14** [cuynu/ytvanced#147]
PLEASE FILL OUT THIS FORM, DO NOT CREATE ISSUE WITHOUT THIS FORM, OTHERWISE, ISSUE WILL CLOSE WITHOUT ANY NOTICE OR CONVERT TO DISCUSSION.

Environment
===========
Platform:Android
OS Version: Android 13
YouTube Vanced Version: 17.28.35
Vanced MicroG: 
Device: galaxy s21

Description
===========
Playlist skipping around videos. Not being able to select a video as it will skip between different ones constantly.

Steps to reproduce
==================
1. Chose a video on a playlist
2. Let the video start playing
3. Chose another video on the playlist and it will jump between different videos and not play the one you want
4.

Expected result
===============
Selected video should play normally

Actual result
=============
Video selection jumps between videos on playlist and doesn't play the selected video

Screenshots / Videos / Logs
===========================

https://youtu.be/tFmfhdIaoPg

Video log uploaded to YouTube

Notes
=====
Doesn't always happen, but very annoying when trying to listen to music or watch a particular video on a playlist

**Comment by cuynu** [comment]
please tell me actual YouTube version in application info (not in YouTube settings -> About)

**Comment by cuynu** [comment]
17.45.36 are not supported anymore, please use 18.01.38 or above
