### ISSUE TITLE
[Bug] Can't install the 18.02.33 Hotfix apk - Parsing Error

### ISSUE THREAD

**Issue by Upsette-Baguette** [cuynu/ytvanced#148]
PLEASE FILL OUT THIS FORM, DO NOT CREATE ISSUE WITHOUT THIS FORM, OTHERWISE, ISSUE WILL CLOSE WITHOUT ANY NOTICE OR CONVERT TO DISCUSSION.

Environment
===========
Platform: Android
OS Version: Magic 4.2.0.134
YouTube Vanced Version: Vanced Version:18.02.33 Hotfix
Vanced MicroG: 0.2.26.225014
Device: Honor X8 5G

Description
===========
After uninstalling the previous version of MicroG, and installing version 0.2.26.225014 successfully, I attempt to install the hotfix apk, but get the error "There was a problem while parsing the package."

Steps to reproduce
==================
1. Install Vanced manager.
2. Ensure no version of MicroG is currently installed, then installed 0.2.26.225014
3. Attempt to install YouTube.Vanced.v18.02.33_Monet_Universal_hotfix.apk

Expected result
===============
Installation of hotfix apk

Actual result
=============
Error message "There was a problem while parsing the package."

Screenshots / Videos / Logs
===========================

Notes
=====
Apologies if this is the wrong way to submit this issue, I am new to installing custom apks.

**Comment by cuynu** [comment]
Are you seeing this when download monet variant : (Android 12+ only) ?
Monet theme variant only can install on Android 12 and above.
