### ISSUE TITLE
App not installed [Bug] 

### ISSUE THREAD

**Issue by 0TheWildcat0** [cuynu/ytvanced#149]
PLEASE FILL OUT THIS FORM, DO NOT CREATE ISSUE WITHOUT THIS FORM, OTHERWISE, ISSUE WILL CLOSE WITHOUT ANY NOTICE OR CONVERT TO DISCUSSION.

Environment
===========
Platform:Android
OS Version: EMUI 12
YouTube Vanced Version:18.02.33 Black hotfix
Vanced MicroG: 0.2.27.231413
Device: Huawei P30 Pro

Description
===========
Can't install. It says App not installed. I deleted old vanced and I have enugh space for it. I have had the same problem with Revaced (Don't know about what version it was.) I can still install other apks and orginal vanced just fine. 

Steps to reproduce
==================
1. Uninstalled old vanced
2. Download new MicroG and Vanced YT client. 
3. Tired to install but failed. 
4.

Expected result
===============
New vanced version that fixes YouTube not playing because it needs to be updated. 

Actual result
=============
Fails to install. 

Screenshots / Videos / Logs
===========================

Notes
=====

**Comment by 0TheWildcat0** [comment]
> does you use multiple users or virtual space to install Vanced before?

Multiple users thats probly it! I will test that as soon as I can.

**Comment by ExtremeCaliber** [comment]
Uninstalled previous microg through settings? That's what was wrong for me. Even though I had uninstalled microg from home, it turned out to still be there in app info in settings.

**Comment by 0TheWildcat0** [comment]
> does you use multiple users or virtual space to install Vanced before?

Yes, it was that.
