### ISSUE TITLE
HUAWEI Google Account Login

### ISSUE THREAD

**Issue by AsGSnak** [cuynu/ytvanced#150]
Environment
===========
Platform:Android
OS Version: EMUI 12.0.0
YouTube Vanced Version: 18.02.33
Vanced MicroG: 0.2.27.231413
Device: HUAWEI P40 Lite

Description
===========
Sincce today, I started being unable to play videos on vanced. It told me the videos weren't available on that version. So I had to uninstall MicroG and Vanced and download the latest versions of both. 
They installed fine and I can use Vanced again but I'm not logged in. When I try to add a Google account using MicroG, it tells me that it sent a code to my device. I know for a fact that this method doesn't work on my Huawei, and that's why I always select the "send me an SMS" option. That option was always available everytime I had to login to Google, with Vice or other apps. But now, that option is greyed out, telling me it's not available in this device. So I'm stuck with receiving a 2 number code, which I never receive.. Because I have a HUAWEI and had to do some modifications for Google Services to work. 
What can I do? Do I need to go back to an older MicroG version? 

Steps to reproduce
==================
1. Open YouTube Vanced
2. Try to Login
3. Add new Google account 
4. Select HUAWEI
5. Input email and password 
6. Select "Try Another Way" 

Expected result
===============
I expected the SMS option to be available, and receive an SMS with code to verify login

Actual result
=============
SMS option greyed out

Screenshots / Videos / Logs
===========================

Notes
=====

**Comment by cuynu** [comment]
does normal login without huawei option work?

**Comment by AsGSnak** [comment]
SOLVED!

Uninstalled and reinstalled MicroG and the same time turned off and on again the Google 2-step verification.
Now when I clicked "try another way" the SMS option was not greyed out. Not sure what fixed it.
