### ISSUE TITLE
Unable to access [Bug] 

### ISSUE THREAD

**Issue by WOLF73748** [cuynu/ytvanced#151]
PLEASE FILL OUT THIS FORM, DO NOT CREATE ISSUE WITHOUT THIS FORM, OTHERWISE, ISSUE WILL CLOSE WITHOUT ANY NOTICE OR CONVERT TO DISCUSSION.

Environment
===========
Platform: Android 
OS Version: One UI Version 4.1
YouTube Vanced Version: v18.02.33_Monet_Universe, v18.02.33_Black_Universe, and v18.03.33_Dark_Universal
Vanced MicroG: Unknown as i am unable to find and install micro g
Device: Samsung S10+

Description
===========
Unable to find and download micro g 

Steps to reproduce
==================
1.Dowlnoad from https://github.com/cuynu/ytvanced/releases/tag/18.02.33. Install youtube vanced apk 
2. Launch youtube vanced
3. Error micro g not found
4. Error stuck on screen even when app is closed

Expected result
===============

Actual result
=============

Screenshots / Videos / Logs
===========================
![Screenshot_20230420_152631_YouTube Vanced](https://user-images.githubusercontent.com/131377030/233397746-e8608a49-435a-4aa7-a95a-7e571e0c2a01.jpg)

Notes
=====
Please fix and upated this ASAP

**Comment by cuynu** [comment]
you should install Vanced microG
