### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by AkshatNawal** [cuynu/ytvanced#157]
PLEASE FILL OUT THIS FORM, DO NOT CREATE ISSUE WITHOUT THIS FORM, OTHERWISE, ISSUE WILL CLOSE WITHOUT ANY NOTICE OR CONVERT TO DISCUSSION.

Environment
===========
Platform:Android
OS Version:
YouTube Vanced Version:
Vanced MicroG:
Device:

Description
===========

Steps to reproduce
==================
1.
2.
3.
4.

Expected result
===============

Actual result
=============

Screenshots / Videos / Logs
![Screenshot_20230421_100109_YouTube Music](https://user-images.githubusercontent.com/131426920/233541231-eaab5af1-07dc-428c-be6f-2a7cd998c132.jpg)
![Screenshot_20230421_100131_Vanced microG](https://user-images.githubusercontent.com/131426920/233541237-83ab1af2-3228-4737-a221-f5a81fc99561.jpg)

===========================

Notes
=====

**Comment by cuynu** [comment]
Information is not enough, please open a new issue
