### ISSUE TITLE
youtube music

### ISSUE THREAD

**Issue by senolfndk** [cuynu/ytvanced#16]
are you going to update vanced youtube music
![icon](https://user-images.githubusercontent.com/52818836/195938971-04d42a88-1bf7-43e7-8a6d-367ba89d4345.png)

**Comment by cuynu** [comment]
Please do not request YouTube Vanced/YouTube Music Vanced on issues

**Comment by senolfndk** [comment]
> Lütfen sorunlarla ilgili olarak YouTube Vanced/YouTube Music Vanced'i talep etmeyin

ok

**Comment by cuynu** [comment]
@senolfndk https://github.com/cuynu/ytvanced/releases/download/17.41.34/YouTube.Music.Vanced-v5.28.51_arm64-v8a.apk

**Comment by senolfndk** [comment]
👍
