### ISSUE TITLE
[Bug] Background play will not work without mini-player open.

### ISSUE THREAD

**Issue by Doomguy3232** [cuynu/ytvanced#163]
PLEASE FILL OUT THIS FORM, DO NOT CREATE ISSUE WITHOUT THIS FORM, OTHERWISE, ISSUE WILL CLOSE WITHOUT ANY NOTICE OR CONVERT TO DISCUSSION.

Environment
===========
Platform:Android
OS Version:13
YouTube Vanced Version: 18.02.33
Vanced MicroG: Came with OG Vanced
Device: Samsung Galaxy S22 Ultra 5G with S Pen

Description
===========

Background play will not work without mini-player open. ( im crying about it because it lowers battery life:(  )

Steps to reproduce
==================
1. Play a video
2. Hit home button
3. Close mini- player
4. Weap

Expected result
===============

On old Vanced I just had to hit play in the notification drawer then it would play.

Actual result
=============

Stops playing and I start loosing it.

Screenshots / Videos / Logs
===========================

![Screenshot_20230424_210213_One UI Home](https://user-images.githubusercontent.com/74806214/234156308-79e40bc2-930d-4012-bcd3-45bea4c2adb0.jpg)

Notes
=====

None

**Comment by cuynu** [comment]
Disable Picture-in-Pictures in YouTube settings -> General
