### ISSUE TITLE
App crash

### ISSUE THREAD

**Issue by Redowansky** [cuynu/ytvanced#167]
PLEASE FILL OUT THIS FORM, DO NOT CREATE ISSUE WITHOUT THIS FORM, OTHERWISE, ISSUE WILL CLOSE WITHOUT ANY NOTICE OR CONVERT TO DISCUSSION.

Environment
===========
Platform:Android
OS Version:9.0
YouTube Vanced Version:18.15.40
Vanced MicroG: 0.2.24.220220
Device:Itel vision 1(unisoc processor)

Description
===========
whenever i try to play any video the app crashes after 5-10 min

Steps to reproduce
==================
1.Open the app
2.play any video 
3.After 5-10 minutes it will crash
4.it takes a lot of time to just open the app 

Expected result
===============
it shouldn't crash, doesn't matter how much i use

Actual result
=============
it crashes again and again after playing a video 

Screenshots / Videos / Logs
===========================

Notes
=====
Please fix it as soon as possible

**Comment by cuynu** [comment]
there is no vanced 18.15.40

**Comment by hastalamuerte** [comment]
Same troubles. Try every build , but after 3-5 mins it's fade to black screen with infinity loading. Reinstall many times non root. 
Maybe YouTube block headers of app or something like that?

**Comment by cuynu** [comment]
> @cuynu Same troubles. Try every build , but after 3-5 mins it's fade to black screen with infinity loading. Reinstall many times, delete micro G, non root, try arm8 (I have 9) try universal. Maybe YouTube block headers of app or something like that?

Make sure you using version 18.02.33 and above or 17.34.36 with spoof
Go to YouTube settings -> Vanced settings -> Video -> enable spoof protobuf (if it was enabled by default, re-enable it)

**Comment by hastalamuerte** [comment]
> > @cuynu Same troubles. Try every build , but after 3-5 mins it's fade to black screen with infinity loading. Reinstall many times, delete micro G, non root, try arm8 (I have 9) try universal. Maybe YouTube block headers of app or something like that?
> 
> Make sure you using version 18.02.33 and above or 17.34.36 with spoof
> Go to YouTube settings -> Vanced settings -> Video -> enable spoof protobuf (if it was enabled by default, re-enable it)

I use 18.01.38 , it's latest build released here. And there is no such settings in last dir

**Comment by cuynu** [comment]
> > > @cuynu Same troubles. Try every build , but after 3-5 mins it's fade to black screen with infinity loading. Reinstall many times, delete micro G, non root, try arm8 (I have 9) try universal. Maybe YouTube block headers of app or something like that?
> > 
> > 
> > Make sure you using version 18.02.33 and above or 17.34.36 with spoof
> > Go to YouTube settings -> Vanced settings -> Video -> enable spoof protobuf (if it was enabled by default, re-enable it)
> 
> I use 18.01.38 , it's latest build released here. And there is no such settings in last dir
> 
> Upd. Found new one in ! And yep it's a new pop up. Thanks, will test Seems work fine . Also enable vp9. How much it reduce traffic in % ? Don't see any picture quality reduce .
> 
> Thanks a lot for your work on project

18.01.38 not is latest build
