### ISSUE TITLE
[Bug] Double tap to like doesn't work

### ISSUE THREAD

**Issue by MattiaRaffaele** [cuynu/ytvanced#168]
Environment
===========
Platform: Android
OS Version: 13
YouTube Vanced Version: 18.02.33
Vanced MicroG: 0.2.24.220220
Device: _Samsung Galaxy A71 SM-A715F/DS_

Description
==================
When you watch a short and you decide to like a video by double-tapping the screen sometimes doesn't work.
The thumb animation appears but the thumb up button doesn't become blue as expected and the like count doesn't change

Steps to reproduce
1. Open yt shorts
2. Double tap the center of the screen

**If the problem does not appear try multiple times restarting youtube**

Expected result
===============
It should add the like to the like count of the video and turn the like button blue

Actual result
=============
The like is not added to the like count and the like button remains gray

Screenshots / Videos / Logs

https://user-images.githubusercontent.com/88104208/234642167-d3887d71-cd6e-41d6-8d3e-3e775df137d9.mp4

**Comment by cuynu** [comment]
this is known bug on original youtube

**Comment by roflsunriz** [comment]
I think the problem purely relates to network (especially Youtube's like-dislike-comment etc handling server)

**Comment by cuynu** [comment]
> I think the problem purely relates to network (especially Youtube's like-dislike-comment etc handling server)

yes, its not vanced issue
