### ISSUE TITLE
[Bug] Content not available in this app

### ISSUE THREAD

**Issue by SamuelEnzi** [cuynu/ytvanced#169]
Environment
===========
Platform:Android
OS Version: 12
YouTube Vanced Version: 17.03.38
Vanced MicroG: 0.2.24.220220
Device: A32

Description
===========
when i try to watch a video youtube displays a error message instead of the video. "This content is not available in this app" (error translated from german). The error message is requesting to update the youtube version.

Steps to reproduce
==================
1. try to play any video using the newest version of ytvanced

Expected result
===============
a video playing back.

Actual result
=============
an error message:  "This content is not available in this app"

Screenshots / Videos / Logs
===========================
![image](https://user-images.githubusercontent.com/62288386/234831438-8131a64e-6b7a-4505-bebd-52484430ad0d.png)

**Comment by cuynu** [comment]
Update to unofficial builds : https://github.com/cuynu/ytvanced#download

**Comment by Haimu-ad** [comment]
Bro, this happened with me too and it can be solved by uninstalling micro-g, youtube vanced then reinstalling it and then re-logging again but after that again it will happen to you as I guess google is targeting specific id's. Therefore, you can try logging in with different account. But, according to me the best solution is that you uninstall your existing micro-g and youtube vanced app and download the latest version of both of those apps from this repository:- 
https://github.com/cuynu/ytvanced

It worked for me and I guess it will work for you too.

Thanks !

**Comment by SamuelEnzi** [comment]
> Update to unofficial builds : https://github.com/cuynu/ytvanced#download

Thanks
