### ISSUE TITLE
[Bug] Explore(trending) option not working.

### ISSUE THREAD

**Issue by Haimu-ad** [cuynu/ytvanced#170]
Environment
===========
Platform:Android
OS Version: 12
YouTube Vanced Version:
Vanced MicroG:
Device: Realme Narzo 30

Description
===========
The explore(trending) option disappears after closing and opening the app again.

Steps to reproduce
==================
1. Open vanced settings, go to miscellaneous and click on enable old layout button.
2. Then, restart the app.
3. Explore option will be there at the top.
4. But then close the app and the option will disappear and then you have to repeat the 3 steps above to get it back but it goes away just after closing the app and reopening it.

Expected result
===============
Explore option should be visible on the home page.

Actual result
=============
No explore option is showing on home page.

Screenshots / Videos / Logs
===========================

Notes
=====

**Comment by cuynu** [comment]
Enable old layout is experimental feature
