### ISSUE TITLE
[Bug] YouTube vanced doesn't save the search results 

### ISSUE THREAD

**Issue by sbtcvn** [cuynu/ytvanced#171]
PLEASE FILL OUT THIS FORM, DO NOT CREATE ISSUE WITHOUT THIS FORM, OTHERWISE, ISSUE WILL CLOSE WITHOUT ANY NOTICE OR CONVERT TO DISCUSSION.

Environment
===========
Platform:Android
OS Version: 10
YouTube Vanced Version: 18.02.33
Vanced MicroG: 0.2.27.231612
Device: Huawei p30 lite

Description
===========
I'm using vanced but it doesn't save the search results despite I turned off the Pause search history, please fix it!

Steps to reproduce
==================
1. Uninstall old version 
2. download the latest yt vanced + microg version on this GitHub 
3. install all of them (microg first)
4. tried to seach a video, it showed results but it didn't save search results, i restarted many times but it didn't work

Expected result
===============
I hope this version works well just like its old version 17.03.38

Actual result
=============
it doesn't save the search results despite I turned off the Pause search history

Screenshots / Videos / Logs
===========================

Notes
=====

**Comment by cuynu** [comment]
you must login google account to save search history, this feature has been removed in newer version of YouTube from server-side
