### ISSUE TITLE
[BUG] YT Music Vanced doesn't survive reboots, and even if no reboots, it roll backs to stock YTM

### ISSUE THREAD

**Issue by roflsunriz** [cuynu/ytvanced#173]
Environment
===========
Platform:Android
OS Version:13
YouTube Music Vanced Root Version:5.39.52
Magisk Module Download links: this repository
Device:Google Pixel 6a

Description
===========
1. When I install Youtube Music (YTM) Vanced root variant magisk zip via magisk manager, it doesn't survive reboots, so if I run YTM after reboots, it becomes non-Vanced version.
2. If I install YTM Vanced root magisk zip, and If I keep phone running without reboots, it randomly roll backs to vanilla YTM.

Steps to reproduce
==================
1.Download YTM Vanced root variant magisk zip from this repository
2.Install the zip from magisk manager
3.Reboot your phone, or do nothing
4.YTM Vanced becomes stock YTM
5.Re-install YTM Vanced zip, loop

Expected result
===============
1.After phone reboot, Youtube Music Vanced should survive
2.YTM Vanced must not randomly roll back to vanilla YTM, when phone's power is on

Actual result
============
non-Vanced  Youtube Music app is popping up

Screenshots / Videos / Logs
===========================
I think it doesn't mean screenshots

Notes
=====
I did give it try to uninstall YTM updates completly then I install YTM Vanced magisk zip. But it didn't survive reboots, too.

I also disabled Google Play Store automatic updates, and also using [Exclude Updates from Play Store](https://github.com/yuk7/playstore-excl-upd) to exclude YTM Vanced from manual updates

I'm also using YT Vanced and older Amazon Music (22.3.2, latest version is 23.5.1) and both of them excluding from manual updates, too are surviving reboots, so I think Google Play Store isn't replacing them.

Rolling back to YTM vanilla is happening exact timing of phone reboot, so it also doesn't relates to Google Play Store's automatic updates.

**Comment by cuynu** [comment]
seem like play store replaced it with vanilla ytm through update

**Comment by cuynu** [comment]
that so weird, when i tries on both rooted phone with YTM Vanced module its works fine, there is no problem

**Comment by roflsunriz** [comment]
Is there anything log that I can provide you for debug?

**Comment by cuynu** [comment]
> Is there anything log that I can provide you for debug?

attach magisk log

**Comment by roflsunriz** [comment]
```````
- Copying zip to temp directory
- Installing YTM.Vanced.v5.39.52_arm64-v8a_MagiskModule.zip
- Current boot slot: _b
- Device is system-as-root
*****************
 YT Music Vanced 
 by cuynu 
*****************
*******************
 Powered by Magisk 
*******************
- Extracting module files
* Updating with stock APK is not needed
* Setting Permissions
* Mounting com.google.android.apps.youtube.music
* Optimizing com.google.android.apps.youtube.music
* Done
- Done
再起動
````

**Comment by roflsunriz** [comment]
[magisk_log_2023-04-28T15.36.26.log](https://github.com/cuynu/ytvanced/files/11350643/magisk_log_2023-04-28T15.36.26.log)

**Comment by cuynu** [comment]
Magisk log doesn't helpful..
I have tried on Pixel 3, YTM Vanced module still works fine

**Comment by roflsunriz** [comment]
YT Vanced survives reboot, YTM Vanced doesn't. What's the difference between them? What's other things I can do for debug?

**Comment by cuynu** [comment]
> YT Vanced survives reboot, YTM Vanced doesn't. What's the difference between them? What's other things I can do for debug?

No, that so weird..

**Comment by roflsunriz** [comment]
The module "YT Music Vanced" exists in magisk manager after reboot (I didn't notice)

**Comment by roflsunriz** [comment]
@cuynu I tried this magisk module https://github.com/cuynu/ytvanced/wiki/rootmusic53351
and survives reboot!

**Comment by cuynu** [comment]
> @cuynu I tried this magisk module https://github.com/cuynu/ytvanced/wiki/rootmusic53351 and survives reboot!

thanks, probably in new module has some problem with script.

**Comment by roflsunriz** [comment]
What does mean closed issue? Did you solve the problem in the scripts latest 5.93.52?

**Comment by roflsunriz** [comment]
@cuynu It seems YTM.Vanced.v5.39.52_arm64-v8a_MagiskModule.zip is unchanged, checksum is same

**Comment by cuynu** [comment]
> @cuynu It seems YTM.Vanced.v5.39.52_arm64-v8a_MagiskModule.zip is unchanged, checksum is same

yes, because 5.33.51 not working on most of my devices, idk why on your device its work

**Comment by roflsunriz** [comment]
then you should re-open this issue and keep it until the problem solved, I guess...

**Comment by cuynu** [comment]
project discontinued, tks for using my builds
