### ISSUE TITLE
[Bug] Back button does not work

### ISSUE THREAD

**Issue by Mukitsamees** [cuynu/ytvanced#174]
PLEASE FILL OUT THIS FORM, DO NOT CREATE ISSUE WITHOUT THIS FORM, OTHERWISE, ISSUE WILL CLOSE WITHOUT ANY NOTICE OR CONVERT TO DISCUSSION.

Environment
===========
Platform:Android
OS Version:9/10
YouTube Vanced Version: 18.02.33
Vanced MicroG: 02.27.231413
Device: Ossuret Chinese Android headunit

Description
===========
Hi
The physical back button does nothing. Want to go back and search for another video/song but can't.
 In the previous version it worked ok

Steps to reproduce
==================
1.Play the video and push the button.
2.
3.
4.

Expected result
===============
Button back to work again.

Actual result
=============

Screenshots / Videos / Logs
===========================

Notes
=====

**Comment by Mukitsamees** [comment]
And it does not matter if regular or car version installed

**Comment by cuynu** [comment]
Back button still work when i test

**Comment by Mukitsamees** [comment]
I'll try to do a small video clip then

**Comment by Mukitsamees** [comment]
Here is the video

**Comment by cuynu** [comment]
> VID_20230429_150119.mp4 
> Here is the video

can you use back button in other applications?

**Comment by Mukitsamees** [comment]
Yes, and in vanced too, when there is no full screen.
Tge problem is just in full screen. I can not baco out of it any more when pressing "back" button

**Comment by cuynu** [comment]
> Yes, and in vanced too, when there is no full screen. Tge problem is just in full screen. I can not baco out of it any more when pressing "back" button

I think it is android software issue in car when in full screen, back button not allowed

**Comment by Mukitsamees** [comment]
Had to do reset to my head unit. Installed latest micro g and yt vanced. Still no back button. Now a new problem.
When the video starts playing, sound is coming, but no picture, just grey screen.

**Comment by cuynu** [comment]
> Had to do reset to my head unit. Installed latest micro g and yt vanced. Still no back button. Now a new problem. When the video starts playing, sound is coming, but no picture, just grey screen.

Enable spoof protobuf option in Vanced settings

**Comment by Mukitsamees** [comment]
Did that, off and on, but does not help

**Comment by Mukitsamees** [comment]
Got video playing, had to turn off "receive warning when playing video when driving" but the back button still does not work. Can use in yt menus, but not from video playing

**Comment by cuynu** [comment]
> Got video playing, had to turn off "receive warning when playing video when driving" but the back button still does not work. Can use in yt menus, but not from video playing

Can you try with original youtube?

**Comment by Mukitsamees** [comment]
It does not work eigther.

**Comment by cuynu** [comment]
> It does not work eigther.

then your head unit firmware problem

**Comment by Mukitsamees** [comment]
But with vanced 17..., The last what was on the Vanced manager, it worked flawlessly.

**Comment by cuynu** [comment]
> But with vanced 17..., The last what was on the Vanced manager, it worked flawlessly.

If original YouTube with same version also same results, i can't help
