### ISSUE TITLE
[Bug] Fullscreen video It only rotates to one side 

### ISSUE THREAD

**Issue by Taranthule** [cuynu/ytvanced#175]
PLEASE FILL OUT THIS FORM, DO NOT CREATE ISSUE WITHOUT THIS FORM, OTHERWISE, ISSUE WILL CLOSE WITHOUT ANY NOTICE OR CONVERT TO DISCUSSION.

Environment
===========
Platform:Android
OS Version:
YouTube Vanced Version:
Vanced MicroG:
Device:

Description
===========

Steps to reproduce
==================
1.
2.
3.
4.

Expected result
===============

Actual result
=============

Screenshots / Videos / Logs
===========================

Notes
=====

**Comment by cuynu** [comment]
Insufficient information
