### ISSUE TITLE
[Bug] YouTube downloads do not complete 

### ISSUE THREAD

**Issue by Garrison42** [cuynu/ytvanced#177]
Youtube downloads do not complete downloading

Environment
===========
Platform:Android
OS Version: EMUI 12, no Google Play Services
YouTube Vanced Version:18.02.33 dark universal hot fix
Vanced MicroG:0.2.27.231612
Device:Huawei Nova 7i

Description
Hello 
When I try to download a YouTube video that is 1hr or more it stops at a random %
It can also happen with videos that are 1hr or less but it's mostly prevalent in videos longer than 1hr 
Another problem is I can't pause a  download and resume it again to trouble shoot the problem 

Steps to reproduce
==================
1.Download a video that's 1hour or longer 

Expected result
===============
Video should complete 

Actual result
=============
Video stops at a random % and does not complete

Screenshots / Videos / Logs
===========================

![Screenshot_20230429_162736](https://user-images.githubusercontent.com/132146936/235308177-5e7593a6-7656-47ff-8e44-7ba29a01bc9f.jpg)

**Comment by cuynu** [comment]
known issue when enable spoof protobuf

**Comment by Garrison42** [comment]
> known issue when enable spoof protobuf

Thank you so much
