### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by 12bib** [cuynu/ytvanced#179]
Youtube Vanced crashing when trying to open shorts
Environment
===========
Platform:Android
OS Version: 6.0.1
YouTube Vanced Version:17.34
Vanced MicroG:0.27
Device: Samsung galaxy j2 prime

Description
===========

Steps to reproduce
==================
1.
2.
3.
4.

Expected result
===============

Actual result
=============

Screenshots / Videos / Logs
===========================

Notes
=====

**Comment by ScarletDevil25** [comment]
I've experienced this issue as well however updating to version 18.02.33 hotfix. Fixed the problem for me.

**Comment by cuynu** [comment]
> I've experienced this issue as well however updating to version 18.02.33 hotfix. Fixed the problem for me.

older android device only can use 17.34.36

**Comment by cuynu** [comment]
reinstall app

**Comment by cuynu** [comment]
no responde
