### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by stargezax** [cuynu/ytvanced#188]
PLEASE FILL OUT THIS FORM, DO NOT CREATE ISSUE WITHOUT THIS FORM, OTHERWISE, ISSUE WILL CLOSE WITHOUT ANY NOTICE OR CONVERT TO DISCUSSION.

Environment
===========
Platform:Android
OS Version:12.5.2
YouTube Vanced Version:18.02.33
Vanced MicroG:0.2.27.231612
Device:Redmi Note 8

Description
The sign in just show blank, add account but no account show

Steps to reproduce
==================
1.open the app
2.click/tap sign in
3.
4.

Expected result
Just show the account I already logged in

Actual result
Nothing

Screenshots / Videos / Logs
Here
![Screenshot_2023-05-06-21-39-21-465_com mgoogle android gms](https://user-images.githubusercontent.com/131424856/236628062-15026e1f-29e0-4902-95d2-ff959220550e.jpg)
![Screenshot_2023-05-06-21-38-59-946_com vanced android apps youtube music](https://user-images.githubusercontent.com/131424856/236628064-53e3cde3-5211-4c65-b8f2-371809696606.jpg)

Notes
(What am I supposed to write here?)

**Comment by cuynu** [comment]
remove account from Vanced microG then add again

**Comment by stargezax** [comment]
Uh nvm this one idk how to delete

**Comment by cuynu** [comment]
> Uh nvm this one idk how to delete

go to settings -> accounts or uninstall Vanced microG

**Comment by stargezax** [comment]
Shows same result, blank

**Comment by cuynu** [comment]
try reinstall yt music

**Comment by stargezax** [comment]
Same problem

**Comment by cuynu** [comment]
seem like you using miui, please turn on auto start

**Comment by stargezax** [comment]
Doesn't work

**Comment by cuynu** [comment]
> Doesn't work

does normal youtube vanced work?

**Comment by stargezax** [comment]
Yes normal yt vanced works

**Comment by cuynu** [comment]
Weirdest problem

**Comment by cuynu** [comment]
can you try older version?

**Comment by stargezax** [comment]
MMM still same

**Comment by cuynu** [comment]
> MMM still same

try enable auto start for Vanced microG

**Comment by stargezax** [comment]
Already did that
Same result

**Comment by cuynu** [comment]
hmm why its so weird, because i have redmi note 8 with same miui version but no problem
