### ISSUE TITLE
I beg you to add option to hide comments

### ISSUE THREAD

**Issue by Maj-ew** [cuynu/ytvanced#189]
Since this Vanced apk isn't patchable in revanced then I beg you to add option to hide all these cringe half brain comments, it's just too much pain and revanced is being detected by google and shadowbanned for few days so can't use it.

**Comment by cuynu** [comment]
I don't want Vanced become ReVanced, i only provide basic features of Vanced. If you want hide comment, use your ReVanced

**Comment by cuynu** [comment]
ReVanced can't be detected by Google because its has spoof signature verification.
