### ISSUE TITLE
Pip not working 

### ISSUE THREAD

**Issue by vskalerana** [cuynu/ytvanced#19]
**Describe the bug**
The PiP mode is not displaying the video instead it is showing comments. 

Whenever we minimize the player by clicking home button it does not show the playing video but instead shows comments in the PiP window. 
![Uploading Screenshot_2022-10-18-19-00-49-172_com.mi.android.globallauncher.jpg…]()

**Please complete the following information:**
 - Device: [e.g. POCO F1 device]
 - OS: [e.g. Android 10]
 - YouTube Vanced Version [e.g. 17.41.3X]
- Vanced MicroG version [e.g. 20220230]

**Comment by cuynu** [comment]
I can't see your screenshot, please reupload.

**Comment by rajarshikhatua100** [comment]
mine is working just fine

**Comment by cuynu** [comment]
No any responses from you. Close issue.
