### ISSUE TITLE
[Bug] Video freezing/buffering

### ISSUE THREAD

**Issue by WOLF73748** [cuynu/ytvanced#192]
PLEASE FILL OUT THIS FORM, DO NOT CREATE ISSUE WITHOUT THIS FORM, OTHERWISE, ISSUE WILL CLOSE WITHOUT ANY NOTICE OR CONVERT TO DISCUSSION.

Environment
===========
Platform:Android 12
OS Version: UI 4.1
YouTube Vanced Version:YouTube.Vanced.v18.01.38_Monet_Universal.apk
Vanced MicroG: MicroG Apk 0.2.27.231612
Device: Samsung S10+

Description
===========
Video keeps freezing/buffering everytime i watch a video. It happens 10 second to 1 minute into the video.

Steps to reproduce
==================
1. Launch youtube vanced 
2. Select a video
3. Play the video
4. Video freezes/buffering

Expected result
===============
Video to play smoothly

Actual result
=============
Video constantly freezing/buffering

Screenshots / Videos / Logs
===========================

https://github.com/cuynu/ytvanced/assets/131377030/06ff34fa-8a48-4029-80d9-8891f39066c8

Notes
=====

Please fix this

**Comment by cuynu** [comment]
use 18.02.33 to fix video playback issue
