### ISSUE TITLE
[BUG] Camera usage indicator shows up when rotated.

### ISSUE THREAD

**Issue by wirekuro** [cuynu/ytvanced#193]
Issue: camera usage indicator shows up when the phone is rotated to right. (When the front camera is in the top right corner of the phone.)
Had this issue in previous versions too.

https://github.com/cuynu/ytvanced/releases/download/18.01.38/YouTube.Vanced.v18.01.38_Black_MagiskModule.zip

![IMG_20230510_065756](https://github.com/cuynu/ytvanced/assets/75095332/1fc75357-94eb-40f1-86b7-190e91354b7f)
![Screenshot_2023-05-10-07-27-08-744_com android settings-edit](https://github.com/cuynu/ytvanced/assets/75095332/bc20f0b2-2987-47be-997e-c84e1342b9c5)

![IMG_20230510_065814](https://github.com/cuynu/ytvanced/assets/75095332/1f1a42ed-3d6a-4746-981c-486315f152ec)
![IMG_20230510_070857](https://github.com/cuynu/ytvanced/assets/75095332/3ed174dd-9ca1-42b6-8dc9-e25c270f2439)

**Comment by cuynu** [comment]
you not fill into issue template, please create new issue.

**Comment by cuynu** [comment]
This probably not app issue, MIUI suck issue
