### ISSUE TITLE
Mixes tab not loading

### ISSUE THREAD

**Issue by RejectedSmile** [cuynu/ytvanced#195]
When at the top of the home page you can see a bunch of tabs one of which is mixes that has created play lists for music and sometimes videos of stuff you would like, as of late when I tap on the tab it loads for a second but no playlist appear I have been messaging with someone setting but nothing should have disabled mixes, possible a issue with YTs side or it could be a user client side Eather way would love some help or would like to know if it an issue with the APK at the moment and would be fixed in the next update

**Comment by cuynu** [comment]
pls create new issue with issue template. insufficient information
