### ISSUE TITLE
[Bug] video download stops after few seconds

### ISSUE THREAD

**Issue by BLACKRHINOthe47** [cuynu/ytvanced#196]
PLEASE FILL OUT THIS FORM, DO NOT CREATE ISSUE WITHOUT THIS FORM, OTHERWISE, ISSUE WILL CLOSE WITHOUT ANY NOTICE OR CONVERT TO DISCUSSION.

Environment
===========
Platform:Android
OS Version: 10
YouTube Vanced Version: 18.02.33
Vanced MicroG: 0.2.26.225014
Device: Samsung Galaxy M11

Description
===========
When trying to download a video it just stops after few seconds until force-stopping the app then it resumes and stops after few seconds again.

Steps to reproduce
==================
1.open the app
2.find a downloadable video, the size better be 20MB or more
3.download it and wait until the download progress stops

Expected result
===============
The downloading process should be done completely without any issues

Actual result
=============
The downloading process stops at one point and refuses to resume

Screenshots / Videos / Logs
===========================
None required

Notes
=====
Sometimes it resumes on its own but only after several hours after being disconnected from the network

**Comment by cuynu** [comment]
Use external downloader inside video player

**Comment by BLACKRHINOthe47** [comment]
> Use external downloader inside video player

It's not working
