### ISSUE TITLE
Create button cannot be hidden.

### ISSUE THREAD

**Issue by MankMeo** [cuynu/ytvanced#20]
**Describe the bug**
Although I have disabled the create button in the menu, it still shown in the home page. 

**To Reproduce**
Update youtube vanced to newest version, turn off create button in the settings, go back to home page. 

**Expected behavior**
The create button must be hidden.

**Screenshot/Videos**
![Screenshot_2022-10-19-15-40-08-716_com vanced android youtube](https://user-images.githubusercontent.com/44147551/196641284-095de6e2-cef1-4c21-b9b4-5054173fa698.jpg)

![Screenshot_2022-10-19-15-39-38-196_com vanced android youtube](https://user-images.githubusercontent.com/44147551/196641358-c9650577-df11-48a6-a06b-a39fec459fc7.jpg)

**Please complete the following information:**
 - Device: [Xiaomi Redmi 8]
 - OS: [Android 11]
 - YouTube Vanced Version [e.g. 17.41.38]
- Vanced MicroG version [e.g. 20220230]

**Additional context**
Add any other context about the problem like logcat,etc here.

**Comment by cuynu** [comment]
Use black theme version to hide create and shorts button. This is a problem in Dark theme version and will be fixed on next version.

**Comment by MankMeo** [comment]
> Use black theme version to hide create and shorts button. This is a problem in Dark theme version and will be fixed on next version.

Ok thank you very much!
