### ISSUE TITLE
[Bug] SponsorBlock

### ISSUE THREAD

**Issue by leSemaleon** [cuynu/ytvanced#207]
PLEASE FILL OUT THIS FORM, DO NOT CREATE ISSUE WITHOUT THIS FORM, OTHERWISE, ISSUE WILL CLOSE WITHOUT ANY NOTICE OR CONVERT TO DISCUSSION.

Environment
===========
Platform:Android 11
OS Version: MIUI 13
YouTube Vanced Version: 18.02.33
Vanced MicroG: 0.2.26.225014
Device: Redmi Note 11

Description
===========
sponsor block does not work correctly.  the embedded ads skip button always appears at the beginning of the video, even if there are no ads.

Steps to reproduce
==================
1.
2.
3.
4.

Expected result
===============

Actual result
=============

Screenshots / Videos / Logs
===========================

Notes
=====

**Comment by cuynu** [comment]
Discontinued
