### ISSUE TITLE
[Bug] Video stops and stays loading

### ISSUE THREAD

**Issue by JunParOfficial** [cuynu/ytvanced#211]
Environment
===========
Platform: Android
OS Version: 11 (LineageOS)
YouTube Vanced Version: 18.21.34
Vanced MicroG: 0.2.27.231712
Device: Samsung Galaxy S5

Description
===========
When playing the video it stops and is in black screen loading, the protobuf It is enabled by default and I try to disable it and the same thing happens as with the activated option.

Any solution to this problem?

Expected result
===============
The video should be viewed normally without loading or buffering problem

Actual result
===============
With reproduction problems

**Comment by cuynu** [comment]
try with original yt app

**Comment by cuynu** [comment]
tbh i can't provide any new updates as it was discontinued, i only here for find solutions

**Comment by JunParOfficial** [comment]
> try with original yt app

What I have done was log out and play a video and this normal charge and I tried with others more and everything works fine. Will logging in again correct the problem?

**Comment by JunParOfficial** [comment]
How strange, the problem only happens to me in one account as I have two YouTube accounts I changed to perform the test and in that account it does not happen only in the main one. Will there be a way to fix it? The only thing I did in that account was to enter youtube through the browser and save some videos for later, can that be?

**Comment by cuynu** [comment]
> How strange, the problem only happens to me in one account as I have two YouTube accounts I changed to perform the test and in that account it does not happen only in the main one. Will there be a way to fix it? The only thing I did in that account was to enter youtube through the browser and save some videos for later, can that be?

i don't know but its maybe temporary issue, and project has been discontinued so you have find new client such as revanced if problem still persists

**Comment by JunParOfficial** [comment]
> > How strange, the problem only happens to me in one account as I have two YouTube accounts I changed to perform the test and in that account it does not happen only in the main one. Will there be a way to fix it? The only thing I did in that account was to enter youtube through the browser and save some videos for later, can that be?
> 
> i don't know but its maybe temporary issue, and project has been discontinued so you have find new client such as revanced if problem still persists

I understand that the project was discontinued, however I tried another client that was YouTube Revanced and the same thing happens but in that account in my other channel (I have two channels with the same account) it does not give me the problem, even with the latest version of your project. One of my channels is the affected the other is not and it is the strange thing.

**Comment by cuynu** [comment]
> > > How strange, the problem only happens to me in one account as I have two YouTube accounts I changed to perform the test and in that account it does not happen only in the main one. Will there be a way to fix it? The only thing I did in that account was to enter youtube through the browser and save some videos for later, can that be?
> > 
> > 
> > i don't know but its maybe temporary issue, and project has been discontinued so you have find new client such as revanced if problem still persists
> 
> I understand that the project was discontinued, however I tried another client that was YouTube Revanced and the same thing happens but in that account in my other channel (I have two channels with the same account) it does not give me the problem, even with the latest version of your project. One of my channels is the affected the other is not and it is the strange thing.

its strange, i have no clue to fix this issue. spoof protobuf is the only way to fix the playback issue for now, if it won't work then you are out of luck

**Comment by JunParOfficial** [comment]
> 

Al parecer es un problema de mi cuenta y no de la app porque de haber sido la app entonces no funcionará la reproducción con ninguna cuenta y hasta sin cuenta si es posible

**Comment by cuynu** [comment]
> > 
> 
> Al parecer es un problema de mi cuenta y no de la app porque de haber sido la app entonces no funcionará la reproducción con ninguna cuenta y hasta sin cuenta si es posible

????

**Comment by JunParOfficial** [comment]
> > > 
> > 
> > 
> > Al parecer es un problema de mi cuenta y no de la app porque de haber sido la app entonces no funcionará la reproducción con ninguna cuenta y hasta sin cuenta si es posible
> 
> ????

I have already solved the problem, I changed the ip on my router so that my cell phone will be changed and I have disabled the protobuf and that way I can watch videos normally but if I activate the protobuf the problem arises again. Thanks a lotI have already solved the problem, I changed the ip on my router so that my cell phone will be changed and I have disabled the protobuf and that way I can watch videos normally but if I activate the protobuf the problem arises again. Thanks a lot 😊
