### ISSUE TITLE
[Bug] `Auto-brightness by swiping` and `Enable save brightness` set brightness to 0% when swiping to exit fullscreen

### ISSUE THREAD

**Issue by ryankhart** [cuynu/ytvanced#212]
Environment
===========
Platform: Android
OS Version: Android 12
YouTube Vanced Version: YouTube.Vanced+.v18.21.34_Black_Universal
Vanced MicroG: Vanced MicroG 0.2.27.231712
Device: OnePlus 7t (Model: HD1905)

Description
===========
When in fullscreen video and when I've set the brightness to auto from inside the Vanced fullscreen video player, and when I swipe down in the middle, the brightness seems to go to 0%, whether I swipe down partially and back up again or whether I swipe down to fully exit fullscreen and then enter fullscreen mode again.

Steps to reproduce
==================
1. Set `Vanced settings` -> `Swipe controls` -> `Enable auto-brightness by swiping` to `on`
2. Set `Vanced settings` -> `Swipe controls` -> `Enable brightness gesture` to `on`
3. Set `Vanced settings` -> `Swipe controls` -> `Experimental Flags` -> `Enable save brightness` to `on`
4. Restart or force quit and relaunch the Youtube Vanced+ app.
5. Start playing a regular YouTube video.
6. Swipe up in the video player to enter fullscreen mode.
7. In fullscreen mode, swipe down on the left side of the screen to set the brightness to 0% which actually sets the brightness to auto, as intended by the chosen Vanced settings.
8. (Option A) Partially swipe down in the middle as if to exit fullscreen mode normally, but without lifting your finger, swipe back up like you just changed your mind and want to stay in fullscreen.
8. (Option B) Swipe down in the middle to exit fullscreen mode, then swipe back up inside the small video player to re-enter fullscreen mode.

Expected result
===============
After the above repro steps, I expect that nothing will change. The brightness stays as it just was before the beginning of the middle swipe down.

Actual result
=============
It seems like it forces the brightness to 0%.

Screenshots / Videos / Logs
===========================
Apologies for not having any video. I tried taking a screen recording, but the brightness of the video does not reflect the brightness of my phone screen.

Notes
=====

**Comment by ryankhart** [comment]
I just noticed that this whole project was discontinued. I wish that this GitHub project had just been archived instead of just a small note about it in a large readme. Archiving the project still keeps it available to anyone who still wants it but makes it very clear that it's not longer supported.

I'll leave you to close this issue when you see this. Thanks for your valued time and effort in creating this tool in the first place.

**Comment by ryankhart** [comment]
In case anyone else looks up this issue after using this version of Vanced, I just finished building my own version of the YouTube app using Revanced Manager using the official YouTube API from apkmirror at version 18.19.35. This issue does not exist as my repro steps in this issue have described, so it seems that it has been fixed already.

**Comment by cuynu** [comment]
Alright, project has been discontinued but i have some plans related to this repository, so I don't archive it
