### ISSUE TITLE
[BUG]Channel watermark doesnt show

### ISSUE THREAD

**Issue by Z3caSilv13** [cuynu/ytvanced#215]
PLEASE FILL OUT THIS FORM, DO NOT CREATE ISSUE WITHOUT THIS FORM, OTHERWISE, ISSUE WILL CLOSE WITHOUT ANY NOTICE OR CONVERT TO DISCUSSION.

Environment
===========
Platform:Android
OS Version:
YouTube Vanced Version:
Magisk Module Download links: 
Device:

Description
===========

Steps to reproduce
==================
1.
2.
3.
4.

Expected result
===============

Actual result
=============

Screenshots / Videos / Logs
===========================

Notes
=====

**Comment by cuynu** [comment]
Insufficient information
