### ISSUE TITLE
[Bug] Channel watermark doesnt show

### ISSUE THREAD

**Issue by Z3caSilv13** [cuynu/ytvanced#216]
PLEASE FILL OUT THIS FORM, DO NOT CREATE ISSUE WITHOUT THIS FORM, OTHERWISE, ISSUE WILL CLOSE WITHOUT ANY NOTICE OR CONVERT TO DISCUSSION.

Environment
===========
Platform:Android
OS Version:
YouTube Vanced Version: 18.02.33
Vanced MicroG: 0.2.26.225014
Device: Samsung Galaxy A23

Description
===========
When i turn on the " Protobuf spoofing to avoid playback issues" the watermark of the channels doesnt show even
turning on.
Steps to reproduce
==================
1.
2.
3.
4.

Expected result
===============

Actual result
=============

Screenshots / Videos / Logs
===========================
![Screenshot_20230703_103418_YouTube Vanced](https://github.com/cuynu/ytvanced/assets/136513896/ffc9b018-93f4-4ac8-807a-2b6cfbfe13ba)

Notes
=====

**Comment by cuynu** [comment]
known issue, wait until i implement my patch or find help in revanced groups
