### ISSUE TITLE
Unable to rewind

### ISSUE THREAD

**Issue by MankMeo** [cuynu/ytvanced#24]
**Describe the bug**
I can't rewind the video with the double tap function. It won't work unless that video is played in vertical mode, or when you 1-tap to pause it. 

**To Reproduce**
1. Double tap while the video is playing
2. Nothing happened

**Expected behavior**
The video must be rewind 1 seconds

**Screenshot/Videos**

![Screenshot_2022-10-22-12-29-30-354_com vanced android youtube](https://user-images.githubusercontent.com/44147551/197322384-30af3184-0cd6-4672-a8b7-cb3f86996db3.jpg)

**Please complete the following information:**
 - Device: Xiaomi Redmi 8
 - OS: Android 10
 - YouTube Vanced Version 17.41.34
- Vanced MicroG version 0.2.24.220220

**Additional context**
Add any other context about the problem like logcat,etc here.

**Comment by cuynu** [comment]
Video rewind working for me on the same video from your screenshot. Please try reinstall app and try again.

**Comment by MankMeo** [comment]
> Video rewind working for me on the same video from your screenshot. Please try reinstall app and try again.

Did you 1-tap on the screen to show the stop button? Or you just use rewind function when the video is playing?

**Comment by cuynu** [comment]
> > Video rewind working for me on the same video from your screenshot. Please try reinstall app and try again.
> 
> Did you 1-tap on the screen to show the stop button? Or you just use rewind function when the video is playing?

I double tap the screen while the video is playing, the video still rewinds to 10 seconds and the video controls don't appear at all

**Comment by MankMeo** [comment]
> > > Video rewind working for me on the same video from your screenshot. Please try reinstall app and try again.
> > 
> > 
> > Did you 1-tap on the screen to show the stop button? Or you just use rewind function when the video is playing?
> 
> I double tap the screen while the video is playing, the video still rewinds to 10 seconds and the video controls don't appear at all

Oh, thanks for letting me know. I will try again and see if the bug is from my device @@

**Comment by MankMeo** [comment]
> > > Video rewind working for me on the same video from your screenshot. Please try reinstall app and try again.
> > 
> > 
> > Did you 1-tap on the screen to show the stop button? Or you just use rewind function when the video is playing?
> 
> I double tap the screen while the video is playing, the video still rewinds to 10 seconds and the video controls don't appear at all

I found out what happened with my Youtube Vanced. I must turn on "Brightness Gesture" to rewind. If I turn it off, I can't double-tap to seek without showing Overlay Button. Can you help me to fix it? I don't want to enable Brightness Gesture. I just want to double-tap to seek.

**Comment by MankMeo** [comment]
I also tried Youtube Revanced at Modyolo but this bug still occurred. I think this bug is from Youtube Original, not modded version.

**Comment by cuynu** [comment]
No, unless the patches fix this issue

**Comment by cuynu** [comment]
Issue can be fixed by turn off both brightness gesture and volume gesture.
