### ISSUE TITLE
History not registering 

### ISSUE THREAD

**Issue by Githubuser12233221** [cuynu/ytvanced#26]
Hello thanks for your work and for the continuation of this fine project. I'm having a history watched problem and I'm hoping you can help me

**Describe the bug**
I'm using the latest version of your non rooted version atm but I also used the rooted one. I have watched several videos but none of them logged as "history". My setting are on default so the history is not paused.

**Please complete the following information:**
 - Device: Xiaomi mi 11t pro
 - OS: Android 12.5
 - YouTube Vanced Version 17.41.34
- Vanced MicroG version 0.2.25.223212

**Comment by Arjun-Ingole** [comment]
> Hello thanks for your work and for the continuation of this fine project. I'm having a history watched problem and I'm hoping you can help me
> 
> **Describe the bug** I'm using the latest version of your non rooted version atm but I also used the rooted one. I have watched several videos but none of them logged as "history". My setting are on default so the history is not paused.
> 
> **Please complete the following information:**
> 
>     * Device: Xiaomi mi 11t pro
> 
>     * OS: Android 12.5
> 
>     * YouTube Vanced Version 17.41.34
> 
>     * Vanced MicroG version 0.2.25.223212

Are you using Ad Away or something similar by any chance

**Comment by shantanub08** [comment]
> Are you using Ad Away or something similar by any chance

Thank you very much! I've been trying to find the reason behind this for half of this year! I confirm the problem was indeed AdAway.

**Comment by Arjun-Ingole** [comment]
> > Are you using Ad Away or something similar by any chance
> 
> Thank you very much! I've been trying to find the reason behind this for half of this year! I confirm the problem was indeed AdAway.

You can just whitelist s.youtube.com and also keep using Adaway

**Comment by cuynu** [comment]
Issue closed. This issue just because Ad Away blocked s.youtube.com.
