### ISSUE TITLE
banking app detect magisk module

### ISSUE THREAD

**Issue by SEAL300** [cuynu/ytvanced#28]
**Describe the bug**
i have magisk with magisk denylist and saftynet pass every banking app was working just fine but whenever i install the module the banking start detecting root "i did hide YouTube app with HMA but it still detect root if i disable this module the banking app work again .
i just want a way to hide the module,i installed micro g and non root version and every thing is fine.

**Please complete the following information:**
 - Device: [e.g. Android device]
 - OS: [e.g. Android 11]
 - YouTube Vanced Version [e.g. 17.03.38]
- Vanced MicroG version [e.g. 20220230]

**Additional context**
Add any other context about the problem like logcat,etc here.

**Comment by cuynu** [comment]
This module only have an simple commands so its can't be affect to your Magisk hide denylist, and why you need hide YouTube app with HMA?

**Comment by SEAL300** [comment]
i tried to hide it but it didn't affect the banking app,is there anyway to install the root version without the module?!

**Comment by cuynu** [comment]
> i tried to hide it but it didn't affect the banking app,is there anyway to install the root version without the module?!

Try hide it with other method

**Comment by cuynu** [comment]
> i tried to hide it but it didn't affect the banking app,is there anyway to install the root version without the module?!

Try hide it with other method

**Comment by SEAL300** [comment]
like what,need some help here

**Comment by cuynu** [comment]
> like what,need some help here

Take Magisk log i and screenshot in banking apps that detect root and upload here
