### ISSUE TITLE
I don't know what you say

### ISSUE THREAD

**Issue by Mehedi5585** [cuynu/ytvanced#29]
I don't know what you say
Swipe to refresh not working some times, please fix this issue

**Comment by cuynu** [comment]
See this
https://github.com/cuynu/ytvanced/issues/13

**Comment by cuynu** [comment]
This is workaround:
Tap on any suggestions/filters on top of the home tab and pull down to refresh will start to work

If you want to permanently solve this issue
Turn off the "Settings > Vanced settings > Ad settings > General layout ad removal" toggle 

Then ads will appear in YouTube Vanced home feed, but pull-down refresh and back-key functionality will work in the home feed.
