### ISSUE TITLE
Download counts :

### ISSUE THREAD

**Issue by VICTOR-KENES** [cuynu/ytvanced#33]
Download counts : 
[![Download counts](https://img.shields.io/github/downloads/cuynu/ytvanced/17.43.36/total?logo=github)](https://github.com/cuynu/ytvanced/releases/tag/17.43.36)

Used tools :
- Revanced-cli-v2.15.1.jar by inotia00
- Revanced-integrations-v0.66.0.apk by inotia00
- Revanced-patches-v2.102.1.jar by inotia00

Applied patches:
[See on releases](https://github.com/cuynu/ytvanced/releases/tag/17.43.36)

<hr /><em>This discussion was created from the release <a href='https://github.com/cuynu/ytvanced/releases/tag/17.43.36'>17.43.36</a>.</em>

_Originally posted by @cuynu in https://github.com/cuynu/ytvanced/discussions/30_

**Comment by VICTOR-KENES** [comment]
brings the beta versions too, 17.44.34 up

**Comment by cuynu** [comment]
DO NOT CREATE ISSUE WITH UPDATE REQUEST

**Comment by VICTOR-KENES** [comment]
Ok
