### ISSUE TITLE
17.43.36 Can't work add to playlist 

### ISSUE THREAD

**Issue by Avtroman** [cuynu/ytvanced#34]
While press "add to playlist" - no playlist show

**Comment by cuynu** [comment]
Disable any VPN service that active on your phone or AdAway (If have) then try again. If still not working, try download official YouTube client and add your video to playlist then go back to YouTube Vanced

**Comment by Ayush77766** [comment]
Not working![IMG_20221112_121407.jpg](https://user-images.githubusercontent.com/117022583/201461315-1144b09c-aca0-408d-898f-2a3a99aed009.jpg)

**Comment by Startrek852** [comment]
I'm having the same problem on the same version. I'm on Android 12 if that helps.

**Comment by cuynu** [comment]
Please reinstall apps and try again. I also have an device with Android 12 and Android 13 and does not have this problem

**Comment by Ayush77766** [comment]
Yes
I have Android 11

**Comment by cuynu** [comment]
> Yes I have Android 11

Try force disable new YouTube layout on Vanced Extended settings then try again

**Comment by Startrek852** [comment]
> Please reinstall apps and try again. I also have an device with Android 12 and Android 13 and does not have this problem

Already done that, still doesn't work.

**Comment by cuynu** [comment]
> > Please reinstall apps and try again. I also have an device with Android 12 and Android 13 and does not have this problem
> 
> Already done that, still doesn't work.

Try force disable new YouTube layout on Vanced Extended settings then try again

**Comment by Startrek852** [comment]
> > > Please reinstall apps and try again. I also have an device with Android 12 and Android 13 and does not have this problem
> > 
> > 
> > Already done that, still doesn't work.
> 
> Try force disable new YouTube layout on Vanced Extended settings then try again

That works, thanks!

**Comment by cuynu** [comment]
Solution is force disable new YouTube layout on Vanced Extended settings then playlist will works. This problem may in server-side of YouTube.

![IMG_20221112_151042_750](https://user-images.githubusercontent.com/90895715/201465340-45196eca-b332-4282-8ced-e5b590de63cd.jpg)

**Comment by Avtroman** [comment]
![Screenshot_20221112-120750758](https://user-images.githubusercontent.com/42459158/201467208-713efc0b-d816-4077-9b62-a2784d99fbbf.jpg)
Helped disable new interface in experimental settings

**Comment by cuynu** [comment]
> ![Screenshot_20221112-120750758](https://user-images.githubusercontent.com/42459158/201467208-713efc0b-d816-4077-9b62-a2784d99fbbf.jpg) Helped disable new interface in experimental settings

Then save to playlist work or not?

**Comment by Ayush77766** [comment]
I try (re install) but not wearking☹️☹️

**Comment by Startrek852** [comment]
> I try (re install) but not wearking☹️☹️ And desibal new layout

Try updating to 17.45.34, it's fixed now for me without disabling new YouTube layout.

**Comment by cuynu** [comment]
> > I try (re install) but not wearking☹️☹️ And desibal new layout
> 
> Try updating to 17.45.34, it's fixed now for me without disabling new YouTube layout. 

Mine working fine, even on 17.43.36. I don't know why he can't save to playlist on their device
