### ISSUE TITLE
Full screen gestures not work 

### ISSUE THREAD

**Issue by Avtroman** [cuynu/ytvanced#37]
Video gestures work first 1-3 run, after this can't work. Video with fields

**Comment by cuynu** [comment]
Please record a video reproduce your issue then upload here

**Comment by Avtroman** [comment]
> Please record a video reproduce your issue then upload here

https://photos.app.goo.gl/yzHdhLkSqwr39cL88

**Comment by cuynu** [comment]
Which version are you using? Did you tried wipe app data and try again?

**Comment by Avtroman** [comment]
> Which version are you using? Did you tried wipe app data and try again?

17.43.3
Wipe data can't helped. On Asus ZE620KL work ok, on Samsung galaxy a51 gestures to full screen can't work

**Comment by cuynu** [comment]
> > Which version are you using? Did you tried wipe app data and try again?
> 
> 17.43.3 Wipe data can't helped. On Asus ZE620KL work ok, on Samsung galaxy a51 gestures to full screen can't work

Try disable new YouTube layout on Vanced Extended settings then try again

**Comment by cuynu** [comment]
If still not working, enable this options temporary 
![Screenshot_20221114-172303_YouTube](https://user-images.githubusercontent.com/90895715/201636925-2d4b4c6e-8bbd-4696-83c6-2731546c04aa.png)

**Comment by cuynu** [comment]
I have tested on Samsung Galaxy Note 10+ with OneUI 4.1 Android 12, full screen gesture still working. Maybe is in accessibility settings

**Comment by Avtroman** [comment]
> I have tested on Samsung Galaxy Note 10+ with OneUI 4.1 Android 12, full screen gesture still working. Maybe is in accessibility settings
Worked for 1-3-4-5 video. Next, need to change any options that requires restart. And, from begin, worked for 1-5 videos

**Comment by cuynu** [comment]
Solution is after change any options that require restart, close current playing video and reopen it.

**Comment by cuynu** [comment]
> Same problem here on 17.43.36, have disabled new YouTube layout and enabled Zoom to fill screen, gestures still don't work. Can't zoom in, adjust volume, or adjust brightness.

What is device name? Android version?, Record screen and upload it here

**Comment by cuynu** [comment]
Mine working fine

**Comment by Startrek852** [comment]
> > Same problem here on 17.43.36, have disabled new YouTube layout and enabled Zoom to fill screen, gestures still don't work. Can't zoom in, adjust volume, or adjust brightness.
> 
> What is device name? Android version?, Record screen and upload it here

OnePlus 8T, Android 12. There's nothing to record because literally nothing happens when I try to do any gestures.

**Comment by cuynu** [comment]
i don't know why, try use official version

**Comment by Ayush77766** [comment]
Root version

**Comment by cuynu** [comment]
Mine working fine, even on Samsung devices with same OneUI version. I don't know why on your device can't
