### ISSUE TITLE
Vance Manager (non-root) has no option to open or update 

### ISSUE THREAD

**Issue by YesTrustMe** [cuynu/ytvanced#38]
Unlike the original,  we could manually check for updates and update. But there's no way this is possible now. As soon as you install the apk,  only DONE is shown and OPEN is greyed out.

I also had to use a third party utility to find an uninstall micro G Vance Manager.

**Comment by cuynu** [comment]
You can check for new release by watch or subscribe this repository, If you want to uninstall microG, go to app list on your phone settings then uninstall. I don't want to do Vanced Manager, because it's more complicated to install Vanced.
