### ISSUE TITLE
17.28.34 crashing, bugs

### ISSUE THREAD

**Issue by deividAlfa** [cuynu/ytvanced#5]
Thanks for contiuing the work!

Sadly I'm having several issues
Android 12 (Oxygen OS 12), non-rooted, microG installed, logged in.

- Random crashes
- Entering configuration crashes instantly 
- 3 dot button not working

![IMG_20220819_044319](https://user-images.githubusercontent.com/48562135/185532023-aa5d72ea-ef34-4889-8fbf-497de03b2a02.jpg)

![IMG_20220819_044610](https://user-images.githubusercontent.com/48562135/185532027-7addc7d8-0e61-4a0d-bd66-44d64506e446.jpg)

**Comment by cuynu** [comment]
Sorry, i didn't continue this work because my skill is bad
That's 17.28.34 version is modified YouTube Vanced version by Vanced Extended project and i only share an APK installation so i can't help you.
