### ISSUE TITLE
Adaptive-(Monochrome)-Icon is broken

### ISSUE THREAD

**Issue by heinrich26** [cuynu/ytvanced#51]
**Describe the bug**
The Themed-Icons Version of the App-Icon doesn't show the Vanced-Icon, but an awkward down-arrow.

**To Reproduce**
1. Go to your Homescreen settings / 'Wallpaper & Style'
2. Enable 'Themed icons'
3. Return to the Homescreen

**Expected behavior**
The Icon should show the YouTube (Vanced) Icon

**Screenshot**
![Image of the badlooking Icon](https://cdn.discordapp.com/attachments/882241112729862174/1043486881301671946/Screenshot_20221119-122349.png)

 - Device: any
 - OS: Android 13
 - YouTube Vanced Version 17.45.34

**Additional context**
The `mipmap-anydpi/ic_launcher.xml` and `mipmap-anydpi/ic_launcher_round.xml` have got something wrong with their `<monochrome />`-Tag, linking to `drawable/ad_spinner_textfield_background_material.xml`, which is definitely not the right drawable for the icon. (I checked, it's offset by -3, probably a resource linking error on the ReVanced side)

**How to work around it**
I used APK Editor Studio to inspect and edit the broken `mipmap-anydpi/ic_launcher.xml` / `mipmap-anydpi/ic_launcher_round.xml`, changing the `<monochrome />`-Tag back to `@drawable/adaptive_monochrome_ic_youtube_launcher`.
Before being able to save the APK again, I had to make some changes in `values-v31/colors.xml`, because it would refuse to compile otherwise. Just change the `@android` to `@*android` for the values, the compiler complains about. :)

**Comment by cuynu** [comment]
Issue solved, but now my network connection not able to upload fixed files so i will upload tomorrow.

**Comment by cuynu** [comment]
File reuploaded, please redownload and install then see monochrome adaptive icon.
