### ISSUE TITLE
Comment and like botton layout not properly visible when system dark theme is enabled

### ISSUE THREAD

**Issue by spidy2356** [cuynu/ytvanced#54]
PLEASE FILL OUT THIS FORM, DO NOT CREATE ISSUE WITHOUT THIS FORM, OTHERWISE, ISSUE WILL CLOSE. 

**Describe the bug**

When system dark theme is enabled the comments section and like botton layout is not displayed as boxy curved white botton as native YouTube client

**To Reproduce**

**Expected behavior**

**Screenshot/Videos**
If applicable, upload screenshot or videos to help explain your problem.
![Screenshot_2022-11-21-12-11-40-153_com google android youtube](https://user-images.githubusercontent.com/101243689/202982559-313c1adb-c4c4-41df-82f0-d3b078e70758.jpg)
![Screenshot_2022-11-21-12-11-20-131_com vanced android youtube](https://user-images.githubusercontent.com/101243689/202982571-30d91643-f97f-4768-99b4-a78ee4fd8cd9.jpg)

 - Device: [e.g. Android device] poco x2
 - OS: [e.g. Android 11] Android 11
 - YouTube Vanced Version [e.g. 17.03.38] 17.45.34
- Vanced MicroG version [e.g. 20220230] 0.2.24.220220

**Additional context**
Add any other context about the problem like logcat,etc here.

**Comment by cuynu** [comment]
You're using MIUI, please remove YouTube Vanced from individual apps in Settings -> Display -> More dark mode options

**Comment by spidy2356** [comment]
Thank you for your response so fast. It works.
