### ISSUE TITLE
MinMicroG-NoGoolag and vanced

### ISSUE THREAD

**Issue by mrjshzk** [cuynu/ytvanced#58]
Doesn't work with the latest [MinMicrog-NoGoolag](https://github.com/FriendlyNeighborhoodShane/MinMicroG_releases/releases), needs additional vanced microg to work. Is there possible integration within No-Goolag?

**Comment by cuynu** [comment]
Vanced microG and microG is different. YouTube Vanced non-root only can use Vanced microG (com.mgoogle.android.gms) and its impossible to integration with MinMicroG or MicroG.

If you want to use YouTube Vanced with MicroG, please use YouTube Vanced root (Magisk Module)

**Comment by mrjshzk** [comment]
Yes I am aware, I should have been more clear. I'm talking about the magisk module. After installing it and rebooting the app immediately crashes. Using the latest magisk and A12 custom rom ([ArrowOS](https://arrowos.net))

**Comment by mrjshzk** [comment]
Yes, normal app works fine. And ReVanced patched youtube as root also works fine under native microG

**Comment by cuynu** [comment]
Try install again and show installation log. By default, while install YouTube Vanced module in this repository, its will directly open YouTube after success installation

**Comment by cuynu** [comment]
And make sure ReVanced does not replace the YouTube app, because after a patch, patcher probably can create a service file in /data/adb/ to replace YouTube with ReVanced on every reboot

**Comment by mrjshzk** [comment]
I deleted everything regarding Vanced/ReVanced in /data/adb and it did open the app and work fine.
But after reboot it doesnt open the app/crashes
![WhatsApp Image 2022-11-25 at 11 24 09](https://user-images.githubusercontent.com/115943663/203975908-77074320-59a3-44a6-b7ac-0bb180b485b4.jpeg)

**Comment by mrjshzk** [comment]
I think I finally got it working.
Completely removed everything about Vanced/ReVanced (the apps and the files inside /data/adb) and removed the magisk module then rebooted.
After that I installed the module and rebooted and it seems to be working fine.
Many thanks :)
