### ISSUE TITLE
Theme issues in areas

### ISSUE THREAD

**Issue by xNovaHD** [cuynu/ytvanced#59]
**Describe the bug**
Theme (Black) does not maintain in certain areas.
Black theme changes momentarily to white theme when entering any vanced featured settings.

The notification of adding a video to a playlist, is white themed.

The notification from leaving incognito mode informing you that you're signing in, is white themed.

**To Reproduce**
Ordered in the order of mentioned above
1. Click on account icon
2. Click on Settings
3. Scroll to Vanced settings
4.  Click on Vanced settings
5.  See bug

0. Can Replace "Vanced Settings" on "3." And "4."  with Return youtube dislike, or Sponsorblock settings.

![Screenshot_20221125-042338_YouTube Vanced](https://user-images.githubusercontent.com/82920149/203935417-6bb3030a-171a-4401-bc22-eb579b7962c6.jpg)

![Screenshot_20221125-042341_YouTube Vanced](https://user-images.githubusercontent.com/82920149/203935472-088eb14b-301c-4082-9ff0-1807270910e1.jpg)

Playlist
1. Go to any video
2. Click on Save
3.  See bug

Incognito
1. Go to account icon
2.  Click on turn on incognito
3.  Go to account icon
5.  Click on turn off incognito 
6. See bug

**Expected behavior**
When following steps of said areas mentioned will result in white theme instead of black theme.

 - Device: S-21
 - OS: Android 12
 - YouTube Vanced Version 17.45.34 Black
- Vanced MicroG version 0.2.25.224113

**Comment by cuynu** [comment]
Is you current device theme is Light and not set in Dark theme? If so, after switching the theme in YouTube Vanced to Black/Dark Theme, restart the app and see if the theme changes

**Comment by xNovaHD** [comment]
I swapped to light mode restarted my phone and swapped back to dark, and it fixed the vanced settings theming. 
Playlist and incognito notification are still light themed.

**Comment by cuynu** [comment]
> I swapped to light mode restarted my phone and swapped back to dark, and it fixed the vanced settings theming. 
> Playlist and incognito notification are still light themed.

That's is normal behavior

**Comment by cuynu** [comment]
> I swapped to light mode restarted my phone and swapped back to dark, and it fixed the vanced settings theming. 
> Playlist and incognito notification are still light themed.

That's is normal behavior, the problem occurs even on official YouTube client.
