### ISSUE TITLE
Unable to complete install on actual television (Google TV)

### ISSUE THREAD

**Issue by dslotter** [cuynu/ytvanced#6]
Pressing the center button (select) on the remote does not activate the buttons on the interface. Without this, installation isn't possible.

**Comment by cuynu** [comment]
Use mouse or install similar YouTube 3rd party API open source client that also Block ads, SponsorBlock, useful features same as YouTube Vanced and desgined for Android TV/Google TV : https://github.com/yuliskov/SmartTubeNext

If you still want try to install this YouTube Vanced, use the Downloader app to able install apk apps
