### ISSUE TITLE
I cant watch any videos

### ISSUE THREAD

**Issue by vevakan783** [cuynu/ytvanced#60]
**Describe the bug**
if I try and watch any video that isn't a short, then it just shows the message 'The following content is not available on this app. Watch the content on the latest version of YouTube.'

**To Reproduce**
1. I go to any video, other than YouTube shorts, which don't have this issue
2. instead of the video, it shows that message

**Expected behavior**
I expect it to show me the video, not an error message

**Screenshot/Videos**
![Screenshot_20221125_170700](https://user-images.githubusercontent.com/102613847/204031109-c59a4a89-8467-4587-a6ad-b9791688fb44.png)

- Device: Android device
- OS: Android 13
- YouTube Vanced Version 17.45.34
- Vanced MicroG version 0.2.24.220220

**Additional context**
Youtube shorts do not show this error, they play normally

**Comment by cuynu** [comment]
Please record a video reproduce your issue and upload it here

**Comment by cuynu** [comment]
Seem like its a video playback buffer issue, try enable "Vanced settings -> Extended settings -> Fix video playback buffer issues" toggle and restart the app then try again
![Screenshot_20221126-114648_YouTube Vanced.png](https://user-images.githubusercontent.com/90895715/204072672-126dbdf9-268a-40fe-a4ac-bf10d56cf2a6.png)

**Comment by cuynu** [comment]
4 days passed, no response
Issue will be closed as not planned
