### ISSUE TITLE
Cant login

### ISSUE THREAD

**Issue by FirephoenixX02** [cuynu/ytvanced#61]
PLEASE FILL OUT THIS FORM, DO NOT CREATE ISSUE WITHOUT THIS FORM, OTHERWISE, ISSUE WILL CLOSE. 

**Describe the bug**
Cant login
**To Reproduce**
Add an account and try to login

**Expected behavior**
login
**Screenshot/Videos**
If applicable, upload screenshot or videos to help explain your problem.
It says check your network connection

- Device: [e.g. Android device]
- OS: [e.g. Android 13] Android 8.0.0
- YouTube Vanced Version [e.g. 17.03.38] latest
- Vanced MicroG version [e.g. 20220230] latest
   Don't fill into Vanced microG version if you're
   using YouTube Vanced root [Magisk Module]

**Additional context**
Add any other context about the problem like logcat,etc here.

**Comment by cuynu** [comment]
What is your device, and please take a screenshot of the error when logging in and upload it here

**Comment by FirephoenixX02** [comment]
> here

LG G7 Thinq
Screenshot:
![grafik](https://user-images.githubusercontent.com/81097492/204101275-392112f3-de16-4ab2-ad41-2ed5c2926d62.png)
Ik its in german but i cant change the language, i already change my location in the settings but it still doesnt change the language

**Comment by FirephoenixX02** [comment]
Clearing Cache and Data of Youtube Vanced and MicroG fixed the Problem. You can close the issue.
