### ISSUE TITLE
Network Issues

### ISSUE THREAD

**Issue by FirephoenixX02** [cuynu/ytvanced#62]
PLEASE FILL OUT THIS FORM, DO NOT CREATE ISSUE WITHOUT THIS FORM, OTHERWISE, ISSUE WILL CLOSE. 

**Describe the bug**
App says im not connected to the Internet but I am.
**To Reproduce**
Try to use the apo
**Expected behavior**
Working app with no connection issues
**Screenshot/Videos**
If applicable, upload screenshot or videos to help explain your problem.
Default Youtube "Your not connected to the internet" Screen
- Device: [e.g. Android device] LG G7
- OS: [e.g. Android 13] 8.0.0
- YouTube Vanced Version [e.g. 17.03.38] latest
- Vanced MicroG version [e.g. 20220230] latest
   Don't fill into Vanced microG version if you're
   using YouTube Vanced root [Magisk Module]

**Additional context**
Add any other context about the problem like logcat,etc here.
Can be fixed by complete Wipe of Data and Cache for YouTube Vanced and MicroG, which also deletes all settings, so its not a solution.
This is a variation of the issue i opened before, this time it just affects everything not just the login.

**Comment by cuynu** [comment]
Reinstall Vanced microG then login again

**Comment by FirephoenixX02** [comment]
> Reinstall Vanced microG then login again

So everytime this happens i have to reinstall microG and login again? I would have to reinstall it almost everyday. This happens about every 2 days.

**Comment by cuynu** [comment]
I think your lg g7 can be updated to newer android version, try update.

**Comment by FirephoenixX02** [comment]
> I think your lg g7 can be updated to newer android version, try update.

It can be updated to Android 10 but not on my Device. I dont know whats the Problem and i already contacted support but i cant update mine.

**Comment by cuynu** [comment]
> > I think your lg g7 can be updated to newer android version, try update.
> 
> It can be updated to Android 10 but not on my Device. I dont know whats the Problem and i already contacted support but i cant update mine.

Record a video reproduce your issue and upload here

**Comment by FirephoenixX02** [comment]
> > > I think your lg g7 can be updated to newer android version, try update.
> > 
> > It can be updated to Android 10 but not on my Device. I dont know whats the Problem and i already contacted support but i cant update mine.
> 
> Record a video reproduce your issue and upload here

Its not reproducable it just happens randomly.

**Comment by cuynu** [comment]
Can you try on official 17.03.38 version?, if issue still persists even on official version, problem is in your device.
