### ISSUE TITLE
Wrong user

### ISSUE THREAD

**Issue by adasio98** [cuynu/ytvanced#71]
PLEASE FILL OUT THIS FORM, DO NOT CREATE ISSUE WITHOUT THIS FORM, OTHERWISE, ISSUE WILL CLOSE. 

**Describe the bug**
After installing YouTube vanced using magisk it shows app in settings to be installed on other user.

**To Reproduce**
1. Install Vanced
2.Check settings

**Expected behavior**
Should show in normal apps and be usable for one that tried to install IT.
**Screenshot/Videos**
If applicable, upload screenshot or videos to help explain your problem.

- Device: [e.g. Moto G7 plus]
- OS: [e.g. Android 10]
- YouTube Vanced Version [e.g. 17.45.38]

**Additional context**
Add any other context about the problem like logcat,etc here.

**Comment by cuynu** [comment]
YouTube Vanced should be installed to user 0. Did you use multiple users?

**Comment by adasio98** [comment]
No? I just used nornal magisk install.

**Comment by adasio98** [comment]
[magisk_install_log_2022-12-07T16.39.23.log](https://github.com/cuynu/ytvanced/files/10177574/magisk_install_log_2022-12-07T16.39.23.log)

**Comment by adasio98** [comment]
[magisk_install_log_2022-12-07T18.50.59.log](https://github.com/cuynu/ytvanced/files/10178652/magisk_install_log_2022-12-07T18.50.59.log)

**Comment by cuynu** [comment]
Which magisk version?

**Comment by cuynu** [comment]
Your magisk/device don't let script mount vanced or unmount vanced.
