### ISSUE TITLE
Black box in comment when holding to paste or selecting something to copy

### ISSUE THREAD

**Issue by SuperFurias** [cuynu/ytvanced#72]
PLEASE FILL OUT THIS FORM, DO NOT CREATE ISSUE WITHOUT THIS FORM, OTHERWISE, ISSUE WILL CLOSE. 

**Describe the bug**
When i open the app, and try to go to any video/post/short to comment, if i want to copy or paste something while writing, a black box appears instead

**To Reproduce**
1. Go to 'any yt video/post/short'
2. Click on 'comments'
3. Click on 'write a comment'
4. Write something then try selecting it or pasting something
5. See error

**Expected behavior**
The normal box to copy, paste etc

**Screenshot/Videos**
![Screenshot_2022-12-06-04-05-34-56_7a4090f09f6554852d748ee9fd6f40d3](https://user-images.githubusercontent.com/34806112/205801866-e3fe39ca-26dc-40c4-9f83-5d3961ae90eb.jpg)
![Screenshot_2022-12-06-04-05-46-54_7a4090f09f6554852d748ee9fd6f40d3](https://user-images.githubusercontent.com/34806112/205801875-c9ded967-0cc3-4160-9c0d-7ed60fa5d376.jpg)
### ![Screenshot_2022-12-06-04-05-54-10_7a4090f09f6554852d748ee9fd6f40d3](https://user-images.githubusercontent.com/34806112/205801882-4bceefa4-3846-4063-862c-7f00c6b88711.jpg)
![Screenshot_2022-12-06-04-21-49-25_7a4090f09f6554852d748ee9fd6f40d3](https://user-images.githubusercontent.com/34806112/205806146-15b0d740-d293-474a-85b2-fb9ec25a260f.jpg)

- Device: [Android device, RMX3311]
- OS: [Android 12]
- YouTube Vanced Version [17.45.36 Black and all previous versions (always black)]
- Vanced MicroG version [0.2.25.224113]
   Don't fill into Vanced microG version if you're
   using YouTube Vanced root [Magisk Module]

**Additional context**
I have this problem from the old version of youtube vanced, and the problem appears also on the new youtube vanced, so i want to know if this is my problem or something like that

**Comment by SuperFurias** [comment]
Ps: i don't have this problem on the search bar of vanced, ONLY comments

**Comment by SuperFurias** [comment]
Its like.. text is black instead of white

**Comment by cuynu** [comment]
It seem like special Dark mode from OEM are forcing Dark mode even Dark mode is enabled. Try find dark mode options and exclude YouTube Vanced from individual apps

**Comment by SuperFurias** [comment]
But i don't have dark mode from OEM enabled

**Comment by SuperFurias** [comment]
my problem is similar to this video
https://youtu.be/S5hl1qJumsw
but, because i'm using the "black edition" the "box" is completely black

**Comment by cuynu** [comment]
That happen even on the base of YouTube client, there is no fix unless the base fix it

**Comment by roflsunriz** [comment]
Mine too. Yet still I can see the menu (copy,paste etc)
![XRecorder_Edited_07122022_155127](https://user-images.githubusercontent.com/8847851/206109052-ba45692c-b32f-40e1-ab0d-93d7d8d0f67f.jpg)

**Comment by roflsunriz** [comment]
Not Vanced version of Youtube app 17.46.37 has same issue. There is no way to fix unless official Youtube app's issue solved or use older version such as 16.x.x.
Recommend close this issue. This repo can't handle this.
![Fotor_167040007879995](https://user-images.githubusercontent.com/8847851/206122427-973031a7-ffb2-4b1c-a610-34b8f3223d1f.jpg)

**Comment by cuynu** [comment]
> Not Vanced version of Youtube app 17.46.37 has same issue. There is no way to fix unless official Youtube app's issue solved or use older version such as 16.x.x. Recommend close this issue. This repo can't handle this. ![Fotor_167040007879995](https://user-images.githubusercontent.com/8847851/206122427-973031a7-ffb2-4b1c-a610-34b8f3223d1f.jpg)
