### ISSUE TITLE
Fullscreen to PIP to Fullscreen Bug

### ISSUE THREAD

**Issue by roflsunriz** [cuynu/ytvanced#77]
Environment
===========
Platform:Android
OS Version:Android 8.1 EMUI 8.1
Testing Software Version:Vanced Youtube 17.45.36
Vanced MicroG:0.2.25.224113
Device Models:Huawei P20 Pro HW-01K CLT-L0J
Reproducibility Rate:Always

Description
===========
Screen displays wired video player position after performing specific operation. I'm not sure this is specific to this app or official one because I'm not premium.

Steps to reproduce
==================
1.Play videos in fullscreen.
2.Tap home button so app becomes PIP mode.
3.Tap PIP player so it get backs to non PIP mode.
4.Player doesn't become fullscreen mode, you see wired half-positioned player.

Expected result
===============
Becomes fullscreen mode.

Actual result
=============
Player which is looks like rotated it forcefully horizontally.

Workarounds
===========
Minimize player then tap player while playing videos.

Screenshots / Videos / Logs
===========================
playing videos in fullscreen mode
![Screenshot_20221210-125610](https://user-images.githubusercontent.com/8847851/206827918-0de3e930-4e2e-4f64-95f7-8f2794418619.jpg)
pip mode
![Screenshot_20221210-125615](https://user-images.githubusercontent.com/8847851/206827922-2a5f15bf-02ff-401c-88f4-1f6461a202d6.jpg)
bug
![Screenshot_20221210-125622](https://user-images.githubusercontent.com/8847851/206827924-1748eaff-5285-4bfe-bc55-807504220ce2.jpg)
minimize player to fix
![Screenshot_20221210-125635](https://user-images.githubusercontent.com/8847851/206827925-a6cdd925-9c4b-4765-b468-6f8827d1fbca.jpg)
back to normal
![Screenshot_20221210-125647](https://user-images.githubusercontent.com/8847851/206827932-14324ad0-e29a-4bac-b41b-714bea12ed68.jpg)

Notes
=====
I thought this is bug because the fullscreen button didn't work.
And workaround only works if it is playing.
Still helps because there's workaround.

**Comment by cuynu** [comment]
Try wiping the app's data and try again. I don't have an Android 8 device here, but I have tested on Android 9,10,11,12,13 devices. No problem above

**Comment by roflsunriz** [comment]
Wiping data solves issue but recoverying configuration from backup occurs issue again...something settings related this I guess? Because what I did after fresh install of VYT was only configuring.

**Comment by roflsunriz** [comment]
Rewiping data and reconfiguring whole setting caused issue again

**Comment by cuynu** [comment]
What settings did you turn on that led to that problem, are you opening experimental features?

**Comment by roflsunriz** [comment]
No experimental features at all.
I have played with messing around with settings but vanilla setting with few essential setting turned on causes bug already, such as dark mode on, play feed on wifi only, show shorts button on bottom toolbar.

**Comment by cuynu** [comment]
Okay. Let me test on Android 8.1 device

**Comment by cuynu** [comment]
> # Environment
> Platform:Android OS Version:Android 8.1 EMUI 8.1 Testing Software Version:Vanced Youtube 17.45.36 Vanced MicroG:0.2.25.224113 Device Models:Huawei P20 Pro HW-01K CLT-L0J Reproducibility Rate:Always
> 
> # Description
> Screen displays wired video player position after performing specific operation. I'm not sure this is specific to this app or official one because I'm not premium.
> 
> # Steps to reproduce
> 1.Play videos in fullscreen. 2.Tap home button so app becomes PIP mode. 3.Tap PIP player so it get backs to non PIP mode. 4.Player doesn't become fullscreen mode, you see wired half-positioned player.
> 
> # Expected result
> Becomes fullscreen mode.
> 
> # Actual result
> Player which is looks like rotated it forcefully horizontally.
> 
> # Workarounds
> Minimize player then tap player while playing videos.
> 
> # Screenshots / Videos / Logs
> playing videos in fullscreen mode ![Screenshot_20221210-125610](https://user-images.githubusercontent.com/8847851/206827918-0de3e930-4e2e-4f64-95f7-8f2794418619.jpg) pip mode ![Screenshot_20221210-125615](https://user-images.githubusercontent.com/8847851/206827922-2a5f15bf-02ff-401c-88f4-1f6461a202d6.jpg) bug ![Screenshot_20221210-125622](https://user-images.githubusercontent.com/8847851/206827924-1748eaff-5285-4bfe-bc55-807504220ce2.jpg) minimize player to fix ![Screenshot_20221210-125635](https://user-images.githubusercontent.com/8847851/206827925-a6cdd925-9c4b-4765-b468-6f8827d1fbca.jpg) back to normal ![Screenshot_20221210-125647](https://user-images.githubusercontent.com/8847851/206827932-14324ad0-e29a-4bac-b41b-714bea12ed68.jpg)
> 
> # Notes
> I thought this is bug because the fullscreen button didn't work. And workaround only works if it is playing. Still helps because there's workaround.

This bug i just see on 17.41.34, can you reinstall app and try again? Which variant?

**Comment by roflsunriz** [comment]
The variant is Unofficial unroot. Reinstall but problem persists.

**Comment by cuynu** [comment]
Hmm.. I have tried on Android 8.1 devices, but the problem not persists. Can you disable new layout?

**Comment by roflsunriz** [comment]
You mean it experimental feature. Yes I did but nothing change.

**Comment by cuynu** [comment]
Try installing to version 17.03.38, see if the problem still occurs or not

**Comment by roflsunriz** [comment]
With testing 17.03.38 with no changes at all, fullscreen ➡️PIP➡️fullscreen(expected) becomes not fullscreen after all, it is just normal vertical player(which follows my display direction setting).

After configuring all, it is same.

**Comment by cuynu** [comment]
> With testing 17.03.38 with no changes at all, fullscreen ➡️PIP➡️fullscreen(expected) becomes not fullscreen after all, it is just normal vertical player(which follows my display direction setting).
> 
> After configuring all, it is same.

Okay, so this problem occurs even on official version. I can't fix that, because it probably only happens on your device.
