### ISSUE TITLE
Watch History not logged, but is enabled

### ISSUE THREAD

**Issue by jeremyriveradev** [cuynu/ytvanced#78]
Environment
===========
Platform:Android 11 
OS Version: Oxygen 11.2.8.8.LE15AA
YouTube Vanced Version: 17.43.36
Magisk Module Download links: 
Device: OnePlus 9p
Reproducibility Rate: All the time

Description
===========
After installing 17.43.36, my YouTube Watch History no longer is logged. It is the only option I have selected to let Google log.
I installed YT Vanced through the Magisk Module. 
It worked perfectly for about 3 days, then suddenly it stopped logging my Watch History. 
It also doesn't actually like a video If I like a video, or comment anything if I leave a comment.

I've had an old YT Vanced installed since right before the original project got taken down and updates stopped coming through the Vanced Manager. 
After about 6 months or so, I'd thought it's about time to update it, and found this project that is continuing the legacy. Thanks! 

Everything worked well on the old YT Vanced app, and worked for a couple days with 17.43.36 installed.

My Watch history is still logged if I watch YT on any other app or device , including 3rd Party YT apps, or on my computer.

Steps to reproduce
==================
1. Watch a video
2. Go to watch history
3. Videos listed do not include anything watched using YT Vanced

Expected result
===============
See the videos I watched, in the Watch History.

Actual result
=============
Only see video history when those videos were watched on anything that isn't YT Vanced.

Workarounds
===========
Don't use YT Vanced... But I want to.

Screenshots / Videos / Logs
===========================
Where would I grab logs from?

Notes
=====

**Comment by cuynu** [comment]
Check if DNS, or software (Example: AdAway) is blocking the s.youtube.com page

**Comment by jeremyriveradev** [comment]
Oh it was AdAway, I had tried disabling it entirely earlier and that didn't seem to work so I didn't put 2 n 2 together.
But after adding s.youtube.com to the Allowed list, all works as normal again.
Thanks for the help!
