### ISSUE TITLE
Black progress bar while watching videos

### ISSUE THREAD

**Issue by YogiKrishna7** [cuynu/ytvanced#80]
PLEASE FILL OUT THIS FORM, DO NOT CREATE ISSUE WITHOUT THIS FORM, OTHERWISE, ISSUE WILL CLOSE WITHOUT ANY NOTICE OR CONVERT TO DISCUSSION.

Environment
===========
Platform:Android
OS Version:12
YouTube Vanced Version: 17.45.36
Vanced MicroG: 0.2.25.224113
Device: Moto g40 fusion 
Reproducibility Rate: whenever I start a video in landscape 

Description
===========
There's a black line where the progress bar is present in landscape mode which doesn't go away, and the red progress bar is not present instead i get grey buffer bar in potrait mode

Steps to reproduce
==================
1.open YouTube 
2.play any video 
3.turn phone into landscape mode
4.you can see in place of progress bar after the video goes full screen 

Expected result
===============
Normal video without any distractions 

Actual result
=============
Black line in landscape and missing red progress bar in potrait mode 

Workarounds
===========
I can't find any

Screenshots / Videos / Logs
===========================
![Screenshot_20221212-200149](https://user-images.githubusercontent.com/120395997/207076462-b8f8e71b-973d-4d70-ae05-d865e6d076ee.png)

Notes
=====
Hopefully it goes away in next update or something, thank you

**Comment by cuynu** [comment]
I don't see that black line in your screenshot
