### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by nagargit** [cuynu/ytvanced#91]
PLEASE FILL OUT THIS FORM, DO NOT CREATE ISSUE WITHOUT THIS FORM, OTHERWISE, ISSUE WILL CLOSE WITHOUT ANY NOTICE OR CONVERT TO DISCUSSION.

Environment
===========
Platform: Android
OS Version: 11
YouTube Vanced Version: all versions 
Vanced MicroG: all versions
Device: redmi Note 8 pro 

Description
===========
When I choose audio only icon (headphone icon in PIP video) video stops not playing audio only) 

Steps to reproduce
==================
1.
2.
3.
4.

Expected result
===============

Actual result
=============

Screenshots / Videos / Logs
===========================

Notes
=====

**Comment by cuynu** [comment]
Reinstall app and try again

**Comment by nagargit** [comment]
I really did many times!
Reinstalled the apps
Cleared data
Uninstalled and reinstalled again..
Still same issue!
I haven't tried in different mobile, but maybe this issue exits with thus mobile

**Comment by nagargit** [comment]
I really did many times!
Reinstalled the apps
Cleared data
Uninstalled and reinstalled again..
Still same issue!
I haven't tried in different mobile, but maybe this issue exits with this mobile

**Comment by cuynu** [comment]
Enable auto start in app information and disable battery optimization

**Comment by cuynu** [comment]
Miui are cringe, its may kill Vanced to run in background

**Comment by nagargit** [comment]
Hello..
Sorry for the late reply
This feature was running normally in the original Vanced app under miui, I used to run it for years.. Just happened in forks :)
Thank you 🙏🏼
