### ISSUE TITLE
[BUG] Youtube Music ads come back after reboot

### ISSUE THREAD

**Issue by lapwat** [cuynu/ytvanced#93]
Environment
===========
Platform:Android
OS Version: Android 13
YouTube Vanced Version: YouTube Music Vanced 5.33.51 for arm64-v8a
Magisk Module Download links: https://github.com/cuynu/ytvanced/releases/download/17.45.34/YouTube.Music.Vanced.v5.33.51_arm64-v8a_MagiskModule.zip
Device: Xiaomi Redmi K20 Pro

Description
===========
Ads come back if I restart my phone.

Steps to reproduce
==================
1. Install Youtube Music Magisk module
2. Reboot your phone
3. Open Youtube Music
4. Play a song

Expected result
===============
No ads

Actual result
=============
Ads show up

Screenshots / Videos / Logs
===========================
xxx

Notes
=====
Started happening last week

**Comment by cuynu** [comment]
Might be a problem related to mount, please use non-root variant temporary, i will bump new base and fix this soon as possible. I also have your same device

**Comment by cuynu** [comment]
Update to new module version.
