### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by 1942520135** [cuynu/ytvanced#96]
PLEASE FILL OUT THIS FORM, DO NOT CREATE ISSUE WITHOUT THIS FORM, OTHERWISE, ISSUE WILL CLOSE WITHOUT ANY NOTICE OR CONVERT TO DISCUSSION.

Environment
===========
Platform:Android
OS Version: 13
YouTube Vanced Version: YouTube Vanced Unofficial version 17.45.36 Black
Vanced MicroG: Vanced MicroG 0.2.26.224913
Device: Poco M4 Pro

Description
===========
I can't play youtube videos, only loading them

Steps to reproduce
==================
1.
2.
3.
4.

Expected result
===============

Actual result
=============

Screenshots / Videos / Logs
===========================

Notes
=====

**Comment by 1942520135** [comment]
When I logout from google account Vanced Micro g. videos can be played
then I logged back in with another account, it's the same video can't be faked

**Comment by cuynu** [comment]
Go to Settings -> Vanced settings -> Extended settings and enable `Fix video playback buffer` toggle

**Comment by 1942520135** [comment]
it's still just loading
I've done a few things:
1. reinstall vanced
2. change the email account
3. Replace the device

**Comment by cuynu** [comment]
Is you live in Europe?

**Comment by 1942520135** [comment]
Indonesia bro

**Comment by spidy2356** [comment]
Please try this method once......it may help you
1. clear cache of youtube vanced
2. uninstall microvanced G and then reinstall it and login with your email

> Indonesia bro
