### ISSUE TITLE
Playlist popup and description dont show in fullscreen

### ISSUE THREAD

**Issue by Omar05091** [cuynu/ytvanced#98]
Environment
===========
Platform:Android
OS Version:13
YouTube Vanced Version:18.02.33 dark
Vanced MicroG: Vanced.MicroG.v0.2.25.224113.apk
Device: samsung a33 5g

Description
===========
At first installation it works fine and even after multiple restarts of the app and setting changes but after a while it bugs out and the playlist popup and description dont show in fullscreen

Steps to reproduce
==================
1.install
2.open app for a while

Thanks :)

**Comment by cuynu** [comment]
This is a problem already exists in the base. There is no way to fix it. Alternative, you can tap open playlist first, then turn on video full screen.

**Comment by Omar05091** [comment]
Its not a big deal since i returned to the previous stable version (17.45.36)
And the problem is gone like before

But the solution you suggested doesnt work even if i open the playlist tab and go full screen
And if i try opening description in full screen nothing happens

**Comment by cuynu** [comment]
> Its not a big deal since i returned to the previous stable version (17.45.36) And the problem is gone like before
> 
> But the solution you suggested doesnt work even if i open the playlist tab and go full screen And if i try opening description in full screen nothing happens

Okay, since this is only beta version so these problem are inevitable, i checked again, problem are comes from base/original YouTube

**Comment by Omar05091** [comment]
Thanks for the help 

And i really appreciate the effort you put into this project

Keep it up ❤️
